### ISSUE TITLE
wx.py.shell introspect ctypes

### ISSUE THREAD

**Issue by lfriedri** [wxWidgets/Phoenix#1018]
**Operating system**: Windows 10
**wxPython version & source**: version 4.0.3 from via pip
**Python version & source**: winpython 3.6.6

**Description of the problem**:

In the wx.py.shell, autocompletion of ctypes.windll... creates an OSError:

```python
import ctypes
ctypes.windll.

Traceback (most recent call last):
  File "R:\rndthon\core\rndthon_shell.py", line 55, in onChar
    self.OnChar(evt)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\shell.py", line 484, in OnChar
    self.autoCompleteShow(command)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\shell.py", line 1184, in autoCompleteShow
    includeDouble=self.autoCompleteIncludeDouble)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\interpreter.py", line 148, in getAutoCompleteList
    *args, **kwds)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\introspect.py", line 30, in getAutoCompleteList
    includeSingle, includeDouble)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\introspect.py", line 38, in getAttributeNames
    if not hasattrAlwaysReturnsTrue(obj):
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\site-packages\wx\py\introspect.py", line 92, in hasattrAlwaysReturnsTrue
    return hasattr(obj, 'bogu5_123_aTTri8ute')
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\ctypes\__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "R:\winpython_2018-09-03\python-3.6.6.amd64\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
To me it seems that 
```python
hasattr(obj, 'bogu5_123_aTTri8ute')
```
and following
```python
hasattr(obj, special_attrs[i])
```

does not go well together with the `__getattr__` behavior of ctypes (`ctypes.__init__`, line 415...):

```python
def __getattr__(self, name):
     if name[0] == '_':
         raise AttributeError(name)
     dll = self._dlltype(name)
     setattr(self, name, dll)
     return dll
```
I think `__getattr__` should actually raise an AttributeError if name is not known (according to https://docs.python.org/3/library/functions.html#hasattr). Instead, it tries to load the library and raises an OSError if it cannot find the dll.

**Comment by RobinD42** [comment]
While we can probably work around this in pyshell (PRs are welcome) I think, ultimately, the inconsistency is a Python problem and should be reported there.

**Comment by lfriedri** [comment]
Thank you for your reply. After looking into it a little deeper, I totally agree with you. I will first check it in python3.7 and if the problem is still there, I will try to report the bug here: https://bugs.python.org/

**Comment by lfriedri** [comment]
Here is the python bugreport:
https://bugs.python.org/issue34816
