### ISSUE TITLE
Reason: image not found in 4.0.3 in Mac compiled app

### ISSUE THREAD

**Issue by yanone** [wxWidgets/Phoenix#1044]
**Operating system**: MacOS 10.13.6
**wxPython version & source**:  4.0.3, pypi
**Python version & source**:  3.6.0, ActivePython

When running my py2app-compiled Mac app, I get the following traceback:

```python
Traceback (most recent call last):
  File "/Users/yanone/Code/TypeWorldApp/apps/Mac/Type.World.0.1.3.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/yanone/Code/TypeWorldApp/apps/Mac/Type.World.0.1.3.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/yanone/Code/TypeWorldApp/apps/Mac/Type.World.0.1.3.app/Contents/Resources/app.py", line 5, in <module>
    import wx, os, webbrowser, urllib.request, urllib.parse, urllib.error, base64, plistlib, json, datetime, traceback, ctypes
  File "wx/__init__.pyc", line 17, in <module>
  File "wx/core.pyc", line 12, in <module>
  File "wx/_core.pyc", line 14, in <module>
  File "wx/_core.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/yanone/Code/TypeWorldApp/apps/Mac/Type.World.0.1.3.app/Contents/Resources/lib/python3.6/lib-dynload/wx/_core.so, 2): Library not loaded: @loader_path/libwx_osx_cocoau_core-3.0.0.4.0.dylib
  Referenced from: /Users/yanone/Code/TypeWorldApp/apps/Mac/Type.World.0.1.3.app/Contents/Resources/lib/python3.6/lib-dynload/wx/_core.so
  Reason: image not found
```

The same script when run directly (not in a compiled app) runs just fine.
I don't know what to make of it. What do I do?

**Comment by RobinD42** [comment]
Did py2app copy `libwx_osx_cocoau_core-3.0.0.4.0.dylib` into the app bundle? 

If so, did it put it into the same location as `_core.so`?

The `@loader_path` notation in the traceback indicates that `_core.so` is going to look for the shared lib in the same path as the binary that is trying to load it. If py2app is not copying it there by default then you'll either need to find a way to tell it to do so, or you can use the `install_name_tool` to change the relative path the `.so` uses to find the `.dylib`(s).

**Comment by yanone** [comment]
> Did py2app copy libwx_osx_cocoau_core-3.0.0.4.0.dylib into the app bundle?

Yes, it's there, under `/Contents/Frameworks/`, which I guess is `@loader_path`.

> If so, did it put it into the same location as _core.so?

No, `_core.so` is in `/Contents/Resources/lib/python3.6/lib-dynload/wx/`

 > The @loader_path notation in the traceback indicates that _core.so is going to look for the shared lib in the same path as the binary that is trying to load it. If py2app is not copying it there by default then you'll either need to find a way to tell it to do so, or you can use the install_name_tool to change the relative path the .so uses to find the .dylib(s).

I tried inserting the `Framework` folder into `sys.path` (to no avail) and also read a bit into the `macholib` module. There is a method called `macholib.dyld.dyld_loader_search(name, loader_path)` but it seems to only return stuff, not manipulate. It's poorly documented. I didn't get it. In short, I'm lost here. This is not my area.

What puzzles me is that only a few months ago, when I build the last version, everything worked fine and I'm unaware of having changed any software configuration since then. But that doesn’t help, I guess :)

I read from your reply that it's more of a `py2app` issue, isn't it?

**Comment by RobinD42** [comment]
> Yes, it's there, under /Contents/Frameworks/, which I guess is @loader_path.

No, `@loader_path` would be `.../{YourApp.app}/Contents/Resources/lib/python3.6/lib-dynload/wx`. It's the path where the binary which is loading the shared lib is located. The import name in  `_core.so` (and the others there) would need to be changed to something like `@loader_path/../../../../../Frameworks/libwx_osx_cocoau_core-3.0.0.4.0.dylib`, and also the same for the other wx dylibs that are being imported. 

> I read from your reply that it's more of a py2app issue, isn't it?

Yes, I think so.

**Comment by fanyer** [comment]
@yanone  @RobinD42 
a quick workaround: "python setup.py py2app --packages=wx",  
> from the author https://bitbucket.org/ronaldoussoren/py2app/issues/252/py2app-creates-broken-bundles-with

**Comment by Binqiling** [comment]
> @yanone @RobinD42
> a quick workaround: "python setup.py py2app --packages=wx",
> 
> > from the author https://bitbucket.org/ronaldoussoren/py2app/issues/252/py2app-creates-broken-bundles-with

A good way ， the command solved my same issue. Thank a lot !!!!

**Comment by CrazyMcCool** [comment]
thanks to @fanyer i've managed to fix the same issue with PyQt5 (after py2app)
`python3 setup.py py2app --packages=PyQt5` did the trick

I'm guessing this will be helpful for people looking to solve py2app issues for any number of modules
just change the `--packages=` to the module you have an issue with :)

All The Best
Python3.8 on macOS BigSur
