### ISSUE TITLE
pdfviewer using PyMuPDF 

### ISSUE THREAD

**Issue by jkbgbr** [wxWidgets/Phoenix#1177]
**Operating system**: Debian strech, Gnome
**wxPython version & source**:          pypi, 4.0.4. 
**Python version & source**:            python 3.6 in conda environment

**Description of the problem**: wx.lib.pdfviewer.viewer.CalculateDimensions() returns None, early in line 338 if some conditions are not met (e.g. the TopLevelWindow is not shown). Setting self.pagebufferwidth seems to be a side effect of calling CalculateDimensions() and so when the routinge exists early, an AttributeError is thrown.
Note: the same code runs OK under Win10

**Comment by david-hughes** [comment]
As the original author of pdfviewer I'll look into what's happening here, This early exit from CalculateDimensions() was introduced back in May 2013 but with no reason documented unfortunately. 
I only use Windows and MacOS, not Linux. Are you able to provide a minimal, runnable example that demonstrates the problem?

**Comment by jmoraleda** [comment]
Running the latest code from the master branch compiled from source. The following snippet of code (extracted from https://wxpython.org/Phoenix/docs/html/wx.lib.pdfviewer.html?highlight=pdf#usage by removing the button panel) demonstrates the problem:

``` python
import wx
import wx.lib.sized_controls as sc

from wx.lib.pdfviewer import pdfViewer

class PDFViewer(sc.SizedFrame):
    def __init__(self, parent, **kwds):
        super(PDFViewer, self).__init__(parent, **kwds)

        paneCont = self.GetContentsPane()

        self.viewer = pdfViewer(paneCont, wx.ID_ANY, wx.DefaultPosition,
                                wx.DefaultSize,
                                wx.HSCROLL|wx.VSCROLL|wx.SUNKEN_BORDER)

        self.viewer.SetSizerProps(expand=True, proportion=1)


if __name__ == '__main__':
    import wx.lib.mixins.inspection as WIT
    app = WIT.InspectableApp(redirect=False)

    pdfV = PDFViewer(None, size=(800, 600))
    pdfV.viewer.LoadFile(r'/tmp/test.pdf')
    pdfV.Show()

    app.MainLoop()
```
This is the complete output written to the console:

```
pdfviewer using PyMuPDF (GPL)
/usr/local/lib/python3.7/dist-packages/wx/py/buffer.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
17:18:58: Debug: ClientToScreen cannot work when toplevel window is not shown
17:18:58: Debug: ClientToScreen cannot work when toplevel window is not shown
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wx/core.py", line 3307, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/pdfviewer/viewer.py", line 409, in Render
    self.pagebuffer = wx.Bitmap(self.pagebufferwidth, self.pagebufferheight)
AttributeError: 'pdfViewer' object has no attribute 'pagebufferwidth'
17:18:58: Debug: ClientToScreen cannot work when toplevel window is not shown
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wx/core.py", line 3307, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/pdfviewer/viewer.py", line 409, in Render
    self.pagebuffer = wx.Bitmap(self.pagebufferwidth, self.pagebufferheight)
AttributeError: 'pdfViewer' object has no attribute 'pagebufferwidth'
```

**Comment by jmoraleda** [comment]
Another example of this bug occurs if one tries to use `GoPage` immediately after loading, for example, adding the following line between the `LoadFile` and `Show` above 
``` python
pdfV.viewer.GoPage(1)  # pages start at 1
```
produces
```
pdfviewer using PyMuPDF (GPL)
/usr/local/lib/python3.7/dist-packages/wx/py/buffer.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "pdfviewertest.py", line 28, in <module>
    pdfV.viewer.GoPage(1)  # pages start at 1
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/pdfviewer/viewer.py", line 299, in GoPage
    self.Scroll(0, pagenum*self.Ypagepixels/self.GetScrollPixelsPerUnit()[1] + 1)
AttributeError: 'pdfViewer' object has no attribute 'Ypagepixels'
```

**Comment by jmoraleda** [comment]
Removing the early termination test (lines 339 and 340 in `wx.lib.pdfviewer.viewer.CalculateDimensions()` solves the problem on GTK. I will submit a pull request after more thorough testing.
``` python
        if self.winheight < 100:
           return
```
