### ISSUE TITLE
wx.lib.plot 'legend' does not work on PolyBars, PolyHistogram

### ISSUE THREAD

**Issue by da-dada** [wxWidgets/Phoenix#1187]
**Operating system**:
**wxPython version & source**:          
**Python version & source**:            

**Description of the problem**:

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
More info and possibly a code sample is needed.

**Comment by da-dada** [comment]
easy, go to > wx.demo > plot > Plot> Draw9 or 10 > Options > Enable Legend
and watch the console: it’s just not implemented I guess
I think your GUI is very nice and I enjoy it

**Comment by RobinD42** [comment]
Ah, now the title makes sense to me, not sure why it didn't before.

```
TypeError: object is neither PolyMarker or PolyLine instance
Traceback (most recent call last):
  File "/Users/robind/projects/wx/git/Phoenix/wx/lib/plot/examples/demo.py", line 713, in OnPlotDraw10
    self.client.Draw(_draw10Objects())
  File "/Users/robind/projects/wx/git/Phoenix/wx/lib/plot/plotcanvas.py", line 1765, in Draw
    self._Draw(graphics, xAxis, yAxis, dc)
  File "/Users/robind/projects/wx/git/Phoenix/wx/lib/plot/plotcanvas.py", line 1904, in _Draw
    legendTextExt)
  File "/Users/robind/projects/wx/git/Phoenix/wx/lib/plot/plotcanvas.py", line 2273, in _drawLegend
    "object is neither PolyMarker or PolyLine instance")
TypeError: object is neither PolyMarker or PolyLine instance
```

**Comment by da-dada** [comment]
Brexit fever (I hope Europe will survive)
