### ISSUE TITLE
can' install with Pip (arch linux)

### ISSUE THREAD

**Issue by ludiazv** [wxWidgets/Phoenix#1196]
**Operating system**:
```
                   -`                 
                  .o+`                 
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 5.0.5-arch1-1-ARCH
               `+oooooo:               Uptime: 31m
               -+oooooo+:              Packages: 504
             `/:-:++oooo+:             Shell: bash 5.0.2
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           WM: i3
          `/+++ooooooooooooo/`         CPU: Intel Celeron N3450 @ 4x 2.2GHz [40.0°C]
         ./ooosssso++osssssso+`        GPU: intel
        .oossssso-````/ossssss+`       RAM: 466MiB / 5787MiB
       -osssssso.      :ssssssso.     
      :osssssss/        osssso+++.    
     /ossssssss/        +ssssooo/-    
   `/ossssso+/:-        -:/+osssso+-  
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/
```
**wxPython version & source**:          pypi
**Python version & source**:            python 3.5.2 via pyenv with virtual enviroment.

**Description of the problem**:
Trying to install via pip fails. see output

```
    Checking for /tmp/pip-install-wlh9koaq/wxpython/bin/waf-2.0.8...
    "/home/ldiaz/projects/boros/borosConfig/.env/bin/python" /tmp/pip-install-wlh9koaq/wxpython/bin/waf-2.0.8 --wx_config=/tmp/pip-install-wlh9koaq/wxpython/build/wxbld/gtk3/wx-config --gtk3 --python="/home/ldiaz/projects/boros/borosConfig/.env/bin/python" --out=build/waf/3.5/gtk3 configure build
    Setting top to                           : /tmp/pip-install-wlh9koaq/wxpython
    Setting out to                           : /tmp/pip-install-wlh9koaq/wxpython/build/waf/3.5/gtk3
    Checking for 'gcc' (C compiler)          : /usr/bin/gcc
    Checking for 'g++' (C++ compiler)        : /usr/bin/g++
    Checking for program 'python'            : /home/ldiaz/projects/boros/borosConfig/.env/bin/python
    Checking for python version >= 2.7.0     : 3.5.2
    python-config                            : /home/ldiaz/.pyenv/shims/python3.5-config
    Asking python-config for pyembed '--cflags --libs --ldflags' flags : not found
    The configuration failed
    (complete log in /tmp/pip-install-wlh9koaq/wxpython/build/waf/3.5/gtk3/config.log)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" /tmp/pip-install-wlh9koaq/wxpython/bin/waf-2.0.8 --wx_config=/tmp/pip-install-wlh9koaq/wxpython/build/wxbld/gtk3/wx-config --gtk3 --python="/home/ldiaz/projects/boros/borosConfig/.env/bin/python" --out=build/waf/3.5/gtk3 configure build ' failed with exit code 1.
    Finished command: build_py (0m1.280s)
    Finished command: build (0m3.798s)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" -u build.py build' failed with exit code 1.
    
```
The problems is on WAF package. any ideas?

**Comment by RobinD42** [comment]
I've seen errors like this when Python was built without the `--enable-shared` configure flag.

**Comment by ludiazv** [comment]
I installed python via pyenv. Could it be the problem.

**Comment by RobinD42** [comment]
Yes, people have had problems with pyenv that turned out to be that it is not using `--enable-shared`. I don't recall if there is a way to have it do so.

**Comment by ludiazv** [comment]
Thanks @RobinD42. 
I will give it a try. In theory is possible to modify pyenv install options by:
```bash
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install <version>
```
If works I will report it. I think it should be documented in wxPhython page for linux installation to help pyenv users.

**Comment by ludiazv** [comment]
It somehow improved the situation by updating pip & moving to python 3.7. But a new error is show:

```
 [758/869] Linking build/waf/3.7/gtk3/_ribbon.cpython-37m-x86_64-linux-gnu.so
    collect2: error: ld returned 1 exit status
    
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp: In function ‘PyObject* meth_wxPGProperty_AddChild(PyObject*, PyObject*, PyObject*)’:
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:1402:34: warning: ‘void wxPGProperty::AddChild(wxPGProperty*)’ is deprecated [-Wdeprecated-declarations]
                 sipCpp->AddChild(prop);
                                      ^
    In file included from ../../../../ext/wxWidgets/include/wx/wx.h:14,
                     from ../../../../wx/include/wxPython/wxpy_api.h:41,
                     from ../../../../sip/cpp/sipAPI_propgrid.h:3308,
                     from ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:10:
    ../../../../ext/wxWidgets/include/wx/propgrid/property.h:2231:24: note: declared here
         wxDEPRECATED( void AddChild( wxPGProperty* prop ) );
                            ^~~~~~~~
    ../../../../ext/wxWidgets/include/wx/defs.h:654:43: note: in definition of macro ‘wxDEPRECATED’
     #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                               ^
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp: In function ‘PyObject* meth_wxPGProperty_GetValueString(PyObject*, PyObject*, PyObject*)’:
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:3142:69: warning: ‘wxString wxPGProperty::GetValueString(int) const’ is deprecated [-Wdeprecated-declarations]
                 sipRes = new  ::wxString(sipCpp->GetValueString(argFlags));
                                                                         ^
    In file included from ../../../../ext/wxWidgets/include/wx/wx.h:14,
                     from ../../../../wx/include/wxPython/wxpy_api.h:41,
                     from ../../../../sip/cpp/sipAPI_propgrid.h:3308,
                     from ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:10:
    ../../../../ext/wxWidgets/include/wx/propgrid/property.h:1657:28: note: declared here
         wxDEPRECATED( wxString GetValueString( int argFlags = 0 ) const );
                                ^~~~~~~~~~~~~~
    ../../../../ext/wxWidgets/include/wx/defs.h:654:43: note: in definition of macro ‘wxDEPRECATED’
     #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                               ^
    
    Waf: Leaving directory `/tmp/pip-install-nh35k8yr/wxPython/build/waf/3.7/gtk3'
    Build failed
     -> task in '_ribbon' failed with exit status 1 (run with -v to display more information)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" /tmp/pip-install-nh35k8yr/wxPython/bin/waf-2.0.8 --wx_config=/tmp/pip-install-nh35k8yr/wxPython/build/wxbld/gtk3/wx-config --gtk3 --python="/home/ldiaz/projects/boros/borosConfig/.env/bin/python" --out=build/waf/3.7/gtk3 configure build ' failed with exit code 1.
    Finished command: build_py (38m18.534s)
    Finished command: build (49m2.692s)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" -u build.py build' failed with exit code 1.
```

**Comment by ludiazv** [comment]
It somehow improved the situation by updating pip & moving to python 3.7. But a new error is show:

```
 [758/869] Linking build/waf/3.7/gtk3/_ribbon.cpython-37m-x86_64-linux-gnu.so
    collect2: error: ld returned 1 exit status
    
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp: In function ‘PyObject* meth_wxPGProperty_AddChild(PyObject*, PyObject*, PyObject*)’:
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:1402:34: warning: ‘void wxPGProperty::AddChild(wxPGProperty*)’ is deprecated [-Wdeprecated-declarations]
                 sipCpp->AddChild(prop);
                                      ^
    In file included from ../../../../ext/wxWidgets/include/wx/wx.h:14,
                     from ../../../../wx/include/wxPython/wxpy_api.h:41,
                     from ../../../../sip/cpp/sipAPI_propgrid.h:3308,
                     from ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:10:
    ../../../../ext/wxWidgets/include/wx/propgrid/property.h:2231:24: note: declared here
         wxDEPRECATED( void AddChild( wxPGProperty* prop ) );
                            ^~~~~~~~
    ../../../../ext/wxWidgets/include/wx/defs.h:654:43: note: in definition of macro ‘wxDEPRECATED’
     #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                               ^
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp: In function ‘PyObject* meth_wxPGProperty_GetValueString(PyObject*, PyObject*, PyObject*)’:
    ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:3142:69: warning: ‘wxString wxPGProperty::GetValueString(int) const’ is deprecated [-Wdeprecated-declarations]
                 sipRes = new  ::wxString(sipCpp->GetValueString(argFlags));
                                                                         ^
    In file included from ../../../../ext/wxWidgets/include/wx/wx.h:14,
                     from ../../../../wx/include/wxPython/wxpy_api.h:41,
                     from ../../../../sip/cpp/sipAPI_propgrid.h:3308,
                     from ../../../../sip/cpp/sip_propgridwxPGProperty.cpp:10:
    ../../../../ext/wxWidgets/include/wx/propgrid/property.h:1657:28: note: declared here
         wxDEPRECATED( wxString GetValueString( int argFlags = 0 ) const );
                                ^~~~~~~~~~~~~~
    ../../../../ext/wxWidgets/include/wx/defs.h:654:43: note: in definition of macro ‘wxDEPRECATED’
     #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                               ^
    
    Waf: Leaving directory `/tmp/pip-install-nh35k8yr/wxPython/build/waf/3.7/gtk3'
    Build failed
     -> task in '_ribbon' failed with exit status 1 (run with -v to display more information)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" /tmp/pip-install-nh35k8yr/wxPython/bin/waf-2.0.8 --wx_config=/tmp/pip-install-nh35k8yr/wxPython/build/wxbld/gtk3/wx-config --gtk3 --python="/home/ldiaz/projects/boros/borosConfig/.env/bin/python" --out=build/waf/3.7/gtk3 configure build ' failed with exit code 1.
    Finished command: build_py (38m18.534s)
    Finished command: build (49m2.692s)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" -u build.py build' failed with exit code 1.
```

**Comment by RobinD42** [comment]
>  [758/869] Linking build/waf/3.7/gtk3/_ribbon.cpython-37m-x86_64-linux-gnu.so
>    collect2: error: ld returned 1 exit status

Was there anything that looked like error messages before this line? The things after that are for a different extension module and are just warnings.

**Comment by ludiazv** [comment]
No just report this msg. Here is other try. This time pip with verbose option -vvv
```
    [814/869] Compiling sip/cpp/sip_propgridwxPGChoicesData.cpp
    [815/869] Compiling sip/cpp/sip_propgridwxPGChoiceEditor.cpp
    [816/869] Compiling sip/cpp/sip_propgridwxArrayStringProperty.cpp
    [817/869] Compiling sip/cpp/sip_auiwxAuiToolBarEvent.cpp
    [818/869] Compiling sip/cpp/sip_auiwxAuiTabArt.cpp
    [819/869] Compiling sip/cpp/sip_auiwxAuiToolBarArt.cpp
    [820/869] Compiling sip/cpp/sip_auicmodule.cpp
    [821/869] Compiling sip/cpp/sip_auiwxAuiPaneButton.cpp
    [822/869] Compiling sip/cpp/sip_auiwxAuiManager.cpp
    [823/869] Linking build/waf/3.7/gtk3/_propgrid.cpython-37m-x86_64-linux-gnu.so
    collect2: error: ld returned 1 exit status

    Waf: Leaving directory `/tmp/pip-install-foo_w_rn/wxPython/build/waf/3.7/gtk3'
    Build failed
     -> task in '_propgrid' failed with exit status 1 (run with -v to display more information)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" /tmp/pip-install-foo_w_rn/wxPython/bin/waf-2.0.8 --wx_config=/tmp/pip-install-foo_w_rn/wxPython/build/wxbld/gtk3/wx-config --gtk3 --python="/home/ldiaz/projects/boros/borosConfig/.env/bin/python" --out=build/waf/3.7/gtk3 configure build ' failed with exit code 1.
    Finished command: build_py (53m22.785s)
    Finished command: build (64m40.120s)
    Command '"/home/ldiaz/projects/boros/borosConfig/.env/bin/python" -u build.py build' failed with exit code 1.
error
Cleaning up...
  Removing source in /tmp/pip-install-foo_w_rn/wxPython
  Removing source in /tmp/pip-install-foo_w_rn/pefile
  Removing source in /tmp/pip-install-foo_w_rn/future
Removed build tracker '/tmp/pip-req-tracker-9l_fnsmo'
Command "/home/ldiaz/projects/boros/borosConfig/.env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-foo_w_rn/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4o__crmd/install-record.txt --single-version-externally-managed --compile --install-headers /home/ldiaz/projects/boros/borosConfig/.env/include/site/python3.7/wxPython" failed with error code 1 in /tmp/pip-install-foo_w_rn/wxPython/
Exception information:
Traceback (most recent call last):
  File "/home/ldiaz/projects/boros/borosConfig/.env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/ldiaz/projects/boros/borosConfig/.env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/ldiaz/projects/boros/borosConfig/.env/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/ldiaz/projects/boros/borosConfig/.env/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/home/ldiaz/projects/boros/borosConfig/.env/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/ldiaz/projects/boros/borosConfig/.env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-foo_w_rn/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4o__crmd/install-record.txt --single-version-externally-managed --compile --install-headers /home/ldiaz/projects/boros/borosConfig/.env/include/site/python3.7/wxPython" failed with error code 1 in /tmp/pip-install-foo_w_rn/wxPython/
```

**Comment by RobinD42** [comment]
Okay, let's try another way, without pip so it's easier to get the full log. Try these steps:

1. Get wxPython-4.0.4.tar.gz from PyPI and extract it somewhere on your system.

2. Change into the wxPython-4.0.4 folder

3. Using the Python you want to build this for, run `python build.py build_wx`. Based on the fact that your pip builds got past this point I don't expect any problems with this step.

4. Next, run this command `python build.py build_py 2>&1 | tee build.log` This is where your pip builds are failing so it will likely fail again. If so then attach the `build.log` file here.

5. If it happens to succeed somehow then you can build a wheel file with `python build.py bdist_wheel` and then use pip to install that wheel.

**Comment by ludiazv** [comment]
well it did work!!!! :) I created the wheel and then i manage to install wheel without problems.

@RobinD42 many thanks. I think it should be great to publish this solution in the documentation.
