### ISSUE TITLE
pdfviewer on gtk3 using PyMuPDF. Sample code will not run

### ISSUE THREAD

**Issue by jmoraleda** [wxWidgets/Phoenix#1242]
Running on Linux debian buster up to date. (gtk3 python 3.7)
wxpython self compiled from source on master branch

The sample code  for `wx.lib.pdfviewer` as posted at https://wxpython.org/Phoenix/docs/html/wx.lib.pdfviewer.html?highlight=pdf#usage crashes.

This is the code in question:
``` python
import wx
import wx.lib.sized_controls as sc

from wx.lib.pdfviewer import pdfViewer, pdfButtonPanel

class PDFViewer(sc.SizedFrame):
    def __init__(self, parent, **kwds):
        super(PDFViewer, self).__init__(parent, **kwds)

        paneCont = self.GetContentsPane()
        self.buttonpanel = pdfButtonPanel(paneCont, wx.ID_ANY,
                                wx.DefaultPosition, wx.DefaultSize, 0)
        self.buttonpanel.SetSizerProps(expand=True)
        self.viewer = pdfViewer(paneCont, wx.ID_ANY, wx.DefaultPosition,
                                wx.DefaultSize,
                                wx.HSCROLL|wx.VSCROLL|wx.SUNKEN_BORDER)

        self.viewer.SetSizerProps(expand=True, proportion=1)

        # introduce buttonpanel and viewer to each other
        self.buttonpanel.viewer = self.viewer
        self.viewer.buttonpanel = self.buttonpanel


if __name__ == '__main__':
    import wx.lib.mixins.inspection as WIT
    app = WIT.InspectableApp(redirect=False)

    pdfV = PDFViewer(None, size=(800, 600))
    pdfV.viewer.LoadFile(r'a path to a .pdf file')
    pdfV.Show()

    app.MainLoop()
```

and this is the complete error log written to the console:

```
pdfviewer using PyMuPDF (GPL)
/usr/local/lib/python3.7/dist-packages/wx/py/buffer.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    pdfV = PDFViewer(None, size=(800, 600))
  File "test.py", line 12, in __init__
    wx.DefaultPosition, wx.DefaultSize, 0)
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/pdfviewer/buttonpanel.py", line 51, in __init__
    self.CreateButtons()
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/pdfviewer/buttonpanel.py", line 102, in CreateButtons
    self.AddButton(btn)
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/buttonpanel.py", line 1934, in AddButton
    self._mainsizer.Insert(lenChildren-1, btnInfo, 0, wx.ALIGN_CENTER|wx.EXPAND, userData=btnInfo)
  File "/usr/local/lib/python3.7/dist-packages/wx/lib/agw/buttonpanel.py", line 1161, in Insert
    szitem = wx.BoxSizer.Insert(self, before, sz, proportion, flag, border, item)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /home/jorge/vc/Phoenix/ext/wxWidgets/src/common/sizer.cpp(2108) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
```

Note that this is a different problem from that of #1177 since there the offending code is in the viewer itself, while here the crash is produced by the button panel.

**Comment by jmoraleda** [comment]
I am closing the issue, because I have found out that the problem is not specific to the pdf button panel and it comes from `wx.lib.agw.buttonpanel`. I have reported the issue with agw.buttonpanel at #1243.
