### ISSUE TITLE
wx.stc.StyledTextCtrl missing 2 'MultiEdge' methods and 1 constant 'STC_EDGE_MULTILINE'

### ISSUE THREAD

**Issue by TSN-ADMIN** [wxWidgets/Phoenix#1279]
**Operating system**: Microsoft Windows [Version 10.0.18362.145]
**wxPython version**: 4.0.7a1.dev4171+a74d4bd1 msw (phoenix) wxWidgets 3.0.5
**Python version**: v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

**Description of the problem**:

Although documented, wx.stc.StyledTextCtrl is missing 2 'MultiEdge' methods:
- **MultiEdgeAddLine**
- **MultiEdgeClearAll**

and 1 constant:
- **STC_EDGE_MULTILINE**

```python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on wi
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import wx.stc as stc
>>>
>>> stc.STC_ED
stc.STC_EDGE_BACKGROUND stc.STC_EDGE_LINE       stc.STC_EDGE_NONE
>>> stc.STC_EDGE_MULTILINE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.stc' has no attribute 'STC_EDGE_MULTILINE'
>>>
>>> stc.MultiEdgeAddLine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.stc' has no attribute 'MultiEdgeAddLine'
>>>
>>> stc.MultiEdgeClearAll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.stc' has no attribute 'MultiEdgeClearAll'
```

**Comment by mesalu** [comment]
If I'm not mistaken, those methods are added in wxWidgets version 3.1, which means they won't be included in wxPython until wxPython version 4.1.
Are you perchance looking at the documentation for wxPython 4.1?

@RobinD42 If this is correct, then we might want to add a special case to sphinx doc generation to correct the 'since ____' directives.

**Comment by Metallicow** [comment]
Those are in wxPython 4.1
wxPython 4.1.0a1.dev4160+2bfa54af msw (phoenix) wxWidgets 3.1.3 Scintilla 3.7.2

Check your Scintilla Version
```python
print(wx.stc.StyledTextCtrl.GetLibraryVersionInfo().GetVersionString())
```

**Comment by TSN-ADMIN** [comment]
Thanks for the quick response.

@mesalu I was indeed looking at the documentation for wxPython 4.1. Mea culpa for that.

@Metallicow I just upgraded my 4.0.7a1.dev4171+a74d4bd1 to the latest build: **4.1.0a1.dev4164+03ee6dcd** .

The constant STC_EDGE_MULTILINE is now included. **[SOLVED]**

Check my findings below where both 'MultiEdge...' methods _seem to be included in the .pyd and .pyi files_, however are **not callable** from Python. Scintilla Version is OK now. Please analyze.

```python
TSN_ADMIN@issue #1279> ver

Microsoft Windows [Version 10.0.18362.145]

TSN_ADMIN@issue #1279> strings "D:\Dev\Python37\Lib\site-packages\wx\_stc.cp37-win_amd64.pyd"|grep MultiEdge
MultiEdgeClearAll
MultiEdgeAddLine
?MultiEdgeAddLine@wxStyledTextCtrl@@QEAAXHAEBVwxColour@@@Z
?MultiEdgeClearAll@wxStyledTextCtrl@@QEAAXXZ
MultiEdgeClearAll()
MultiEdgeAddLine(column, edgeColour)

TSN_ADMIN@issue #1279> grep -n MultiEdge "D:\Dev\Python37\Lib\site-packages\wx\stc.pyi"
6969:    def MultiEdgeAddLine(self, column, edgeColour):
6971:        MultiEdgeAddLine(column, edgeColour)
6976:    def MultiEdgeClearAll(self):
6978:        MultiEdgeClearAll()

TSN_ADMIN@issue #1279> python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> import wx.stc
>>>
>>> wx.version()
'4.1.0a1.dev4164+03ee6dcd msw (phoenix) wxWidgets 3.1.3'
>>>
>>> wx.stc.StyledTextCtrl.GetLibraryVersionInfo().GetVersionString()
'Scintilla 3.7.2'
>>>
>>> wx.stc.STC_EDG
wx.stc.STC_EDGE_BACKGROUND wx.stc.STC_EDGE_LINE       wx.stc.STC_EDGE_MULTILINE  wx.stc.STC_EDGE_NONE
>>> wx.stc.STC_EDGE_MULTILINE
3
>>>
>>> wx.stc.MultiEdgeAddLine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.stc' has no attribute 'MultiEdgeAddLine'
>>>
>>> wx.stc.MultiEdgeClearAll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx.stc' has no attribute 'MultiEdgeClearAll'
>>>
```

**Comment by Metallicow** [comment]
@TSN-ADMIN 
works for me...

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

""""""

# Imports.--------------------------------------------------------------------
# -Python Imports.
import os
import sys

# -wxPython Imports.
import wx
import wx.stc

class MyStyledTextCtrl(wx.stc.StyledTextCtrl):
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=0, name='styledTextCtrl'):
        wx.stc.StyledTextCtrl.__init__(self, parent, id, pos, size, style, name)

        sci = wx.stc.StyledTextCtrl.GetLibraryVersionInfo().GetVersionString().rstrip()
        self.SetText((((sci + ' ') * 42) + '\n') * 42)

        self.SetEdgeMode(edgeMode=wx.stc.STC_EDGE_MULTILINE)
        self.MultiEdgeAddLine(column=42, edgeColour='#FF0000')
        self.MultiEdgeAddLine(column=79, edgeColour='#00FF00')
        self.MultiEdgeAddLine(column=80, edgeColour='#0000FF')
        ##self.MultiEdgeClearAll()

class MyFrame(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        wxVER = 'wxPython %s' % wx.version()
        pyVER = 'python %d.%d.%d.%s' % sys.version_info[0:4]
        versionInfos = '%s %s' % (wxVER, pyVER)
        self.CreateStatusBar().SetStatusText(versionInfos)
        panel = MyStyledTextCtrl(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

    def OnDestroy(self, event):
        self.Destroy()

class MyApp(wx.App):
    def OnInit(self):
        self.SetClassName('MyApp')
        self.SetAppName('MyApp')
        gMainWin = MyFrame(None)
        gMainWin.SetTitle('MyFrame')
        self.SetTopWindow(gMainWin)
        gMainWin.Center()
        gMainWin.Show()
        return True

if __name__ == '__main__':
    gApp = MyApp(redirect=False,
            filename=None,
            useBestVisual=False,
            clearSigInt=True)
    gApp.MainLoop()

```

**Comment by TSN-ADMIN** [comment]
@Metallicow 
Works like a charm. Must have had a black-out, bad hair day 🤔
Point is I forgot to add **.StyledTextCtrl** in the method calls ...

IOU and issue closed.

![image](https://user-images.githubusercontent.com/28123215/60319694-99ae3680-9977-11e9-973e-1b1b3ae06e3b.png)

```python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import wx.stc

In [2]: wx.stc.StyledTextCtrl.MultiEdgeAddLine?
Docstring:
MultiEdgeAddLine(column, edgeColour)

Add a new vertical edge to the view.
Type:      builtin_function_or_method

In [3]: wx**_.stc.StyledTextCtrl_**.MultiEdgeClearAll?
Docstring:
MultiEdgeClearAll()

Clear all vertical edges.
Type:      builtin_function_or_method
```
