### ISSUE TITLE
TypeError: FlexGridSizer(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by papin1** [wxWidgets/Phoenix#1308]
**Operating system**: Windows 7 Ultimate x64
**wxPython version & source**:  4.0.6
Stock or custom build: stock build
**Python version & source**:   2.7.13 win32
Stock or custom build: stock build
**Description of the problem**:

When running the code sample below, I get the following error:
```python
Traceback (most recent call last):
  File "<module1>", line 20, in <module>
  File "<module1>", line 8, in __init__
TypeError: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: 'hgap' is not a valid keyword argument
  overload 2: 'hgap' is not a valid keyword argument
  overload 3: 'hgap' is not a valid keyword argument
  overload 4: 'hgap' is not a valid keyword argument
```
I decided to take the jump from Classic 3.0.2 to Phoenix. First I installed the beta version 4.1 but since I got the error, I thought it was because of the beta. So I decided to go for the stable release 4.0.6, to no avail.

I use a lot FlexGridSizer with the keywords "rows" or "cols" but not both at the same time because in many instances I do not know in advance how many rows or columns the sizer will contain. FlexGridSizer is my preferred sizer --- I use it everywhere, not only in my form builder.

Strangely, if I replace "rows" by "cols" in the sample there is no error. But with "rows" it does not matter whether the keywords "vgap" and "hgap" appear, there will be the same TypeError with variations in the message, as shown below:
```python
...
    fgs = wx.FlexGridSizer(rows=3)
...
TypeError: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: 'rows' is not a valid keyword argument
  overload 2: 'rows' is not a valid keyword argument
  overload 3: not enough arguments
  overload 4: not enough arguments
```

**Sample**:
```python
import wx

class DemoFrame(wx.Frame):
    def __init__(self, parent=None, **kwargs):
        wx.Frame.__init__(self, parent=None, **kwargs)
        mp = wx.Panel(self)
        labels = ['A', 'B', 'C']
        fgs = wx.FlexGridSizer(rows=3, vgap=10, hgap=5)
        for label in labels:
            btn = wx.Button(mp, wx.ID_ANY, 'Button %s' % label)
            fgs.Add(btn, 0, wx.EXPAND)
        fgs.AddGrowableCol(0)
        sz = wx.BoxSizer()
        sz.Add(fgs, 1, wx.EXPAND|wx.ALL, 10)
        mp.SetSizer(sz)

if __name__ == '__main__':
    app = wx.App()
    frame = DemoFrame()
    frame.Show()
    app.MainLoop()
```

The very same kind of error has been reported in https://github.com/wxWidgets/Phoenix/issues/722

**Comment by papin1** [comment]
I forgot to precise that if I add "cols=1" as in:
```python
fgs = wx.FlexGridSizer(rows=3, cols=1, vgap=10, hgap=5)
```
there is no error.

**Comment by RobinD42** [comment]
The C++ overloads for the constructor look like this:

```
    wxFlexGridSizer( int cols, int vgap, int hgap );
    wxFlexGridSizer( int cols, const wxSize& gap = wxSize(0, 0) );
    wxFlexGridSizer( int rows, int cols, int vgap, int hgap );
    wxFlexGridSizer( int rows, int cols, const wxSize& gap );
```

So at a minimum you must specify at least `cols`, which will match the 2nd constructor. If you want to specify `rows`, then you must also specify `cols` and gaps, to match one of the last 2 constructors above.

In Classic we had just this:

```
        wxFlexGridSizer( int rows=0, int cols=0, int vgap=0, int hgap=0 );
```
although IIRC there were issues if neither `rows` nor `cols` were specified.

**Comment by papin1** [comment]
Thank you Robin. All is clear now.

Well, this is very unfortunate. I will have to edit almost all my FlexGridSizer. Moreover, I specify vgap or hgap but not both if it's not necessary.

I don't understand why the classic constructor has changed so much that it uselessly complicates code either in the C++ part --- 4 alternatives for the constructor instead of only one, if I understand correctly --- and to the users of the widget (raising new issues when there wasn't before, apparently). 

Also, in some cases, XRC (in Classic) complains about the number of rows and cols not matching with FlexGridSizer even if the numbers are correct when both "rows" and "cols" are present. 

Due to this behavior I downgraded from Phoenix to Classic. I feel like it will be easier to me to upgrade to python 3 than to Phoenix if there are other such big changes although some things in Phoenix are better.

Anyway, I don't understand why the C++ part does not include the constructor:
```C
    wxFlexGridSizer( int rows, const wxSize& gap = wxSize(0, 0) );
```
(I could deal with ```gap=(5, 0)``` instead of hgap=5)
Maybe I should make a request (to the C++ wxWidgets team?) asking to revert back to the old constructor?

**Comment by RobinD42** [comment]
> Due to this behavior I downgraded from Phoenix to Classic. I feel like it will be easier to me to upgrade to python 3 than to Phoenix if there are other such big changes although some things in Phoenix are better.

There are no Python3 builds for Classic.


> Anyway, I don't understand why the C++ part does not include the constructor:
>     wxFlexGridSizer( int rows, const wxSize& gap = wxSize(0, 0) );

Because the C++ compiler will not be able to tell the difference between that and the other `(int, const wxSize&)` signature.
