### ISSUE TITLE
Ubuntu Library Error

### ISSUE THREAD

**Issue by RandyERaymond** [wxWidgets/Phoenix#1400]
**Operating system**: Ubuntu 18.04.3 LTS
**wxPython version & source**: 4.0.6 & pip3 from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04
**Python version & source**: Python 3.6 & version that installs with Ubuntu 18.04.3

**Description of the problem**: Here is the traceback from trying to run the wxPython 4.0.6 demo.pyw:
-------------------------------------------
/usr/bin/python3.6 /home/randyeraymond/Documents/SoftwareStuff/Python/wxPython-demo-4.0.6/demo/demo.pyw
Traceback (most recent call last):
  File "/home/randyeraymond/Documents/SoftwareStuff/Python/wxPython-demo-4.0.6/demo/demo.pyw", line 3, in <module>
    import Main
  File "/home/randyeraymond/Documents/SoftwareStuff/Python/wxPython-demo-4.0.6/demo/Main.py", line 62, in <module>
    import wx.adv
  File "/home/randyeraymond/.local/lib/python3.6/site-packages/wx/adv.py", line 13, in <module>
    from ._adv import *
ImportError: libSDL-1.2.so.0: cannot open shared object file: No such file or directory

Process finished with exit code 1
---------------------------------------------------------

**Comment by RobinD42** [comment]
Do you have the `libsdl2` system package installed?
