### ISSUE TITLE
ImportError: MemoryLoadLibrary failed loading wx\_core.pyd

### ISSUE THREAD

**Issue by leileigong** [wxWidgets/Phoenix#1430]
**win7 and win10**:
**wxPython 4.0.6**:          
**Python 2.7**:            

**my app works fine on pycharm.
but when i make an executable file.
i got an error:
Traceback (most recent call last):
  File "ClientWin.py", line 18, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "wx\__init__.pyo", line 17, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "wx\core.pyo", line 12, in <module>
  File "zipextimporter.pyo", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading wx\_core.pyd
**:

my ClientWin.py file like this:

```import wx
from wx import aui
from wx import adv
```

**Comment by RobinD42** [comment]
Which tool are you using to create the executable? Have you tried building with different settings/options for that tool? Specifically, I seem to recall something like this happening with py2exe and the build mode that puts everything in one file.

**Comment by leileigong** [comment]
i use py2exe 0.6.9 create my executable.

here is my py2exe configuration.
`
    OPTS = {"py2exe": {"compressed": 1,
                       "optimize": 1,
                       "bundle_files": 1,
                       "excludes": ["Tkinter", ],
                       'packages': ['pubsub',
                                    'wx._xml'
                                    ],
                        "dll_excludes": ["MSVCP90.dll", "w9xpopen.exe",
                                         "libopenblas.JKAMQ5EVHIVCPXP2XZJB2RQPIN47S32M.gfortran-win32.dll"
                                         ]
                       }
            }


setup(
        name = NAME,
        version = VERSION,
        options = OPTS,
        console = [{"script": APP,
                    "icon_resources": [],
                    "other_resources" : [(RT_MANIFEST, 1,
                                          manifest)],
                  },
                  {"script": "ServerWin.py",
                    "icon_resources": [],
                    "other_resources" : [(RT_MANIFEST, 1,
                                          manifest)],
                  }],
        description = NAME,
        author = AUTHOR,
        author_email = AUTHOR_EMAIL,
        license = LICENSE,
        url = URL,
        zipfile=None,
        data_files = FILES,
        )`

**Comment by leileigong** [comment]
in addition，the same py2exe configration for wxpyton3 works fine.

**Comment by RobinD42** [comment]
I don't remember much of the specifics of py2exe, but I would start by trying different options for the `bundle_files` setting. If that doesn't help then I suggest trying PyInstaller. I've heard more positive things about it lately than py2exe.
