### ISSUE TITLE
Sample program TextBox.py uses undefined color

### ISSUE THREAD

**Issue by tomihasa** [wxWidgets/Phoenix#1531]
**Operating system**: OS X El Capitan 10.11.6
**wxPython version & source**: 4.0.7.post2 (pip)
**Python version & source**: 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Description of the problem**:

Source:

https://github.com/wxWidgets/Phoenix/blob/master/samples/floatcanvas/TextBox.py

What happens:

The program aborts before showing the GUI.

Output:

18:12:49: Debug: wxColour::Set - couldn't set to colour string 'LightBlue'
18:12:49: Debug: wxColour::Set - couldn't set to colour string 'LightBlue'
Traceback (most recent call last):
  File "TextBox.py", line 288, in <module>
    DrawFrame(None, -1, "FloatCanvas Demo App", wx.DefaultPosition, (700,700) )
  File "TextBox.py", line 271, in __init__
    self.Canvas.ZoomToBB()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 802, in ZoomToBB
    self.SetToNewScale(DrawFlag=DrawFlag)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 821, in SetToNewScale
    self.Draw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 628, in Draw
    self._DrawObjects(dc, self._DrawList, ScreenDC, self.ViewPortBB, HTdc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/lib/floatcanvas/FloatCanvas.py", line 986, in _DrawObjects
    Object._Draw(dc, WorldToPixel, ScaleWorldToPixel, HTdc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/lib/floatcanvas/FCObjects.py", line 2006, in _Draw
    dc.SetBrush(self.Brush)
wx._core.wxAssertionError: C++ assertion "retval != __null" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/osx/carbon/graphics.cpp(141) in wxMacCreateCGColor(): 

Workaround:

Use for example color Blue instead of LightBlue.

**Comment by RobinD42** [comment]
The list of built-in color names is fairly limited. As can be seen here: https://docs.wxpython.org/wx.ColourDatabase.html "light blue" is a valid name. You can also use `wx.lib.colourdb` to load a more expansive list of names into the ColourDatabase.
