### ISSUE TITLE
SpeedMeter error with icon when size specified in constructor

### ISSUE THREAD

**Issue by tjohnsonhvac** [wxWidgets/Phoenix#1535]
**Operating system**:   Windows10 x64
**wxPython version & source**:        pypi- 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5
**Python version & source**:            3.7.5 python.org

**Description of the problem**:

if the widget size is defined in the constructor, with the `SM.SM_DRAW_MIDDLE_ICON` agwStyle, it causes the `Draw()` function to be called before the icon is defined throwing an exception.

```python
class FuelMeter2(SM.SpeedMeter):
    def __init__(self, parent, position):
        SM.SpeedMeter.__init__(self, parent, pos=position, size=(200,200), agwStyle=SM.SM_DRAW_HAND | SM.SM_DRAW_PARTIAL_SECTORS | SM.SM_DRAW_MIDDLE_ICON)

        self.SetAngleRange(-math.pi / 3, math.pi / 3)
        intervals = range(0, 5)
        self.SetIntervals(intervals)
        colours = [wx.BLACK] * 3
        colours.append(wx.RED)
        self.SetIntervalColours(colours)
        ticks = ["F", "", "", "", "E"]
        self.SetTicks(ticks)
        self.SetTicksColour(wx.WHITE)
        self.SetHandColour(wx.Colour(255, 255, 0))
        # Define The Icon We Want
        # We Want To Simulate A Car Gas-Control
        icon = wx.Icon("bitmaps/smfuel.ico", wx.BITMAP_TYPE_ICO)
        icon.SetWidth(24)
        icon.SetHeight(24)
        # Draw The Icon In The Center Of SpeedMeter
        self.SetMiddleIcon(icon)
        self.SetSpeedBackground(wx.BLACK)
        self.SetArcColour(wx.WHITE)
        self.SetSpeedValue(0.7)
```
EXCEPTION:
```
Traceback (most recent call last):
  File "C:/Users/cbs0426/PycharmProjects/obd/obd_scanner.py", line 194, in <module>
    main = Main(None)
  File "C:/Users/cbs0426/PycharmProjects/obd/obd_scanner.py", line 186, in __init__
    fuel = FuelMeter2(panel, (800,225))
  File "C:/Users/cbs0426/PycharmProjects/obd/obd_scanner.py", line 70, in __init__
    SM.SpeedMeter.__init__(self, parent, pos=position, size=(200,200), agwStyle=SM.SM_DRAW_HAND | SM.SM_DRAW_PARTIAL_SECTORS | SM.SM_DRAW_MIDDLE_ICON)
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 540, in __init__
    bufferedstyle=bufferedstyle)
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 334, in __init__
    self.doSetWindowCreated(None)
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 342, in doSetWindowCreated
    self.OnSize(None)
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 387, in OnSize
    self.UpdateDrawing()
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 403, in UpdateDrawing
    self.Draw(dc)
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 1046, in Draw
    middleicon = self.GetMiddleIcon()
  File "C:\Users\cbs0426\AppData\Local\Programs\Python\Python37\lib\site-packages\wx\lib\agw\speedmeter.py", line 1573, in GetMiddleIcon
    return self._middleicon
AttributeError: 'FuelMeter2' object has no attribute '_middleicon'
```
looking at the traceback, it looks like manually defining a size causes `UpdateDrawing()` to be called.

A quick fix I did was to add a try, except into the `Draw()` function.

wx/lib/agw/speedmeter.py (LINE: 1044)
```python
        if self._agwStyle & SM_DRAW_MIDDLE_ICON:
            try:
                middleicon = self.GetMiddleIcon()
                middlewidth, middleheight = self.GetMiddleIconDimens()
                middleicon.SetWidth(middlewidth*self.scale)
                middleicon.SetHeight(middleheight*self.scale)
                middleangle = (startangle + endangle)/2.0

                mw = middleicon.GetWidth()
                mh = middleicon.GetHeight()


                newx = centerX + 1.5*mw*cos(middleangle) - mw/2.0
                newy = centerY - 1.5*mh*sin(middleangle) - mh/2.0

                dc.DrawIcon(middleicon, newx, newy)

                # Restore Icon Dimension, If Not Something Strange Happens
                middleicon.SetWidth(middlewidth)
                middleicon.SetHeight(middleheight)
            except:
                print("\nERROR: SpeedMeter does not have a middle icon.")
```
This fixed the issue for now but I'm sure there is a better way to handle this.

**Comment by Metallicow** [comment]
Setting a NullBitmap in the init by default I think should work.
