### ISSUE TITLE
assertion with Freeze / Thaw / PropertyGridManager / DestroyLater

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#1626]
**Operating system**: Windows 10, 64 bit
**wxPython version & source**:         4.1.0 from PyPi
**Python version & source**:            stock 3.6.4, 64 bit

**Description of the problem**: destroying a PropertyGridManager inside Freeze/Thaw triggers an assertion

`Thaw() without matching Freeze()`

Using e.g. `Destroy` instead of `DestroyLater` or using `TextCtrl` instead of `PropertyGridManager` does not trigger the assertion.

E.g. Python 3.8, 64 bit with wxPython 4.0.7 does not trigger the assertion.

With `SetAssertMode(0)` the assertion is ignored.

```python
# -*- coding: UTF-8 -*-

import sys, wx, wx.propgrid

print(sys.version)
print(wx.VERSION)


class MyFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, style=wx.DEFAULT_FRAME_STYLE)

        self.child = wx.propgrid.PropertyGridManager(self)
        #self.child = wx.TextCtrl(self)
        wx.CallAfter(self.destroy_property_grid)

    def destroy_property_grid(self):
        self.Freeze()
        # this triggers an assertion for a PropertyGridManager; OK for a TextCtrl
        self.child.DestroyLater()
        ## this would work:
        #self.child.Destroy()
        self.Thaw()
        self.Refresh()


class App(wx.App):
    def OnInit(self):
        #self.SetAssertMode(0)  # avoid assertion
        self.myframe = MyFrame()
        self.SetTopWindow(self.myframe)
        self.myframe.Show()
        return True


if __name__ == "__main__":
    app = App(0)
    app.MainLoop()
```
Output:
```
3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
(4, 1, 0, '')
Traceback (most recent call last):
  File "d:\Python\Python36-64\lib\site-packages\wx\core.py", line 3383, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "PropGrid_Freeze.py", line 23, in destroy_property_grid
    self.Thaw()
wx._core.wxAssertionError: C++ assertion "m_freezeCount" failed at ..\..\src\common\wincmn.cpp(1287) in wxWindowBase::Thaw(): Thaw() without matching Freeze()
```

**Comment by DietmarSchwertberger** [comment]
Submitted a wxWidgets ticket https://github.com/wxWidgets/wxWidgets/issues/22269

The assertion is actually being triggered by a sequence `Freeze/Hide/Thaw`.

**Comment by DietmarSchwertberger** [comment]
Closing this for now. It will be in wxWidgets 3.1.7.
