### ISSUE TITLE
wx._core.wxAssertionError: -- newer version issue w/widgetsizer.Add(... wx.ALL|wx.ALIGN_RIGHT)

### ISSUE THREAD

**Issue by MMathisLab** [wxWidgets/Phoenix#1635]
**Operating system**: MacOs, Windows 10, Ubuntu 16.04
**wxPython version & source**:    pypi  4.1.0 (windows, MacOS) & source build on ubuntu
**Python version & source**:          anaconda, python 3.7 and python 3.6

**Description of the problem**:

Firstly, thanks for this package - we use it in our package (https://github.com/AlexEMG/DeepLabCut). 3 of our users are hitting the same issue, across platforms. This appears to be the culprit (`widgetsizer.Add(self.quit , 1, wx.ALL|wx.ALIGN_RIGHT, 15)`) code here: https://github.com/AlexEMG/DeepLabCut/blob/9cf2f5a263a4c72bd176414225d64d055bf75858/deeplabcut/generate_training_dataset/labeling_toolbox.py#L216  but has been deployed successfully for the last 1.5+ years; rolling back to, for example, `4.0.7.post2` works as intended. Thanks for any tips on improving our code/if this is indeed a wxPython issue, for the fix :).

```python
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/backends/backend_wx.py", line 844, in _onSize
    self.bitmap = wx.Bitmap(self._width, self._height)
wx._core.wxAssertionError: C++ assertion ""w > 0 && h > 0"" failed at /Users/robind/projects/bb2/dist-osx-py37/build/ext/wxWidgets/src/osx/core/bitmap.cpp(1008) in Create(): invalid bitmap size
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/label_frames.py", line 102, in label_frames
    deeplabcut.label_frames(self.config)
  File "/Applications/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 260, in label_frames
    labeling_toolbox.show(config,imtypes=imtypes)
  File "/Applications/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 701, in show
    frame = MainFrame(None, config, imtypes).Show()
  File "/Applications/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 216, in __init__
    widgetsizer.Add(self.quit , 1, wx.ALL|wx.ALIGN_RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /Users/robind/projects/bb2/dist-osx-py37/build/ext/wxWidgets/src/common/sizer.cpp(2098) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```

**Comment by infinity77** [comment]
I think it’s a bit too extreme (being conservative here) to go nuclear and raise an assertion error just because of sizer flags. Even if the sizer flags are ignored, who cares? Do we need to atomize an entire application just because there’s an additional, redundant wx.ALIGN_RIGHT? Maybe a DeprecationWarning would be better? I understand that it’s not under Phoenix’ control as the assert comes from wxWidgets, but, wxWidgets guys, seriously?

**Comment by Metallicow** [comment]
This is another case related to #1270 I did a while ago. Robin confirmed that it was indeed time to remove them. This has been deprecated/markedForRemoval in wxWidgets for some time, and since wxPython Phoenix finally caught up to wxWidgets, this will probably be reported more. 
There wasn't a release note made in 4.1, but Robin went ahead and made a small note in changelog for 4.1.x that mentions this change.
... But in all reality since it wasn't throwing deprecation messages for whatever reason, wxWidgets should have just outright fixed the problem when it was first noticed instead of prolonging. 
@MMathisLab If you look at the PullReqz #1272 changes it sorta shows what needs changed when upgrading to wxPy 4.1.
While we all feel your pain having to deal with this, doing a search on your whole program python .py files will find most of them unless it may be xml or something else. It is how I dealt with the issue with my software. And just if you are curious, It didn't change anything visually as far as I can tell. Hope this helps.

**Comment by MMathisLab** [comment]
thanks, @Metallicow!
