### ISSUE TITLE
module 'wx' has no attribute 'FONTWEIGHT_LIGHT'

### ISSUE THREAD

**Issue by Shawn-Zhuang** [wxWidgets/Phoenix#1721]
**Operating system**: UBuntu 18.01, docker container
**wxPython version & source**:        about my problem 
**Python version & source**:           anaconda3, python 3.7

**Description of the problem**:

When I run a project code, it shows 
```python
  File "/root/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_wx.py", line 155, in RendererWx
    100: wx.FONTWEIGHT_LIGHT,
AttributeError: module 'wx' has no attribute 'FONTWEIGHT_LIGHT'
```

I thought it was the problem about the wx version, so I conda&pip uninstall wxPython,
however, afterwards I can still import wx in python, and the wx is in the directory  of 
`'/root/anaconda3/lib/python3.7/site-packages/vtk/wx/__init__.py'`

This is wheird....I think there are 2 problem in the above description.

Can anybode help me ？Thanks!

**Comment by Shawn-Zhuang** [comment]
in addition, I can not pip install wxPython
```

(base) root@6e64d0f6dcca:~/SA-SSD# pip install wxPython -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting wxPython
  Downloading http://mirrors.aliyun.com/pypi/packages/cb/4f/1e21d3c079c973ba862a18f3be73c2bbe2e6bc25c96d94df605b5cbb494d/wxPython-4.1.0.tar.gz (65.8MB)
     |████████████████████████████████| 65.8MB 1.3MB/s 
Requirement already satisfied: pillow in /root/anaconda3/lib/python3.7/site-packages (from wxPython) (6.1.0)
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from wxPython) (1.12.0)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from wxPython) (1.16.4)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  ERROR: Complete output from command /root/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ygbioixi/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fpqfmfyf --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/root/anaconda3/bin/python" -u build.py build
  Will build using: "/root/anaconda3/bin/python"
  3.7.3 (default, Mar 27 2019, 22:11:17)
  [GCC 7.3.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.1.0
  
  Running command: build
  Running command: build_wx
  wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
  Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
  /tmp/pip-install-ygbioixi/wxPython/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for toolkit... gtk
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether we are using the Intel C compiler... no
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking whether gcc needs -traditional... no
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking whether we are using the Intel C++ compiler... no
  checking whether we are using the Sun C++ compiler... no
  checking for ar... ar
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for langinfo.h... yes
  checking for wchar.h... yes
  checking for sys/select.h... yes
  checking for cxxabi.h... yes
  checking for an ANSI C-conforming const... yes
  checking for inline... inline
  checking size of short... 2
  checking size of void *... 8
  checking size of int... 4
  checking size of long... 8
  checking size of size_t... 8
  checking size of long long... 8
  checking size of wchar_t... 4
  checking for va_copy... yes
  checking whether the compiler supports variadic macros... yes
  checking for _FILE_OFFSET_BITS value needed for large files... 64
  checking if large file support is available... yes
  checking for _LARGEFILE_SOURCE value needed for large files... no
  checking whether byte ordering is bigendian... no
  checking for std::wstring in <string>... yes
  checking for std::istream... yes
  checking for std::ostream... yes
  checking for type_traits... no
  checking for tr1/type_traits... yes
  checking for __sync_fetch_and_add and __sync_sub_and_fetch builtins... yes
  checking for libraries directories... /usr/lib/x86_64-linux-gnu /usr/lib
  checking for cos... no
  checking for floor... no
  checking if floating point functions link without -lm... no
  checking for sin... yes
  checking for ceil... yes
  checking if floating point functions link with -lm... yes
  checking for strtoull... yes
  checking for pkg-config... /usr/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  configure: WARNING: Defaulting to the builtin regex library for Unicode build.
  checking for zlib.h >= 1.1.4... yes
  checking for zlib.h... (cached) yes
  checking for deflate in -lz... yes
  checking for png.h > 0.90... yes
  checking for png.h... (cached) yes
  checking for png_sig_cmp in -lpng... yes
  checking for jpeglib.h... no
  configure: WARNING: system jpeg library not found, will use built-in instead
  checking lzma.h usability... no
  checking lzma.h presence... no
  checking for lzma.h... no
  checking for jbg_dec_init in -ljbig... no
  checking for LIBTIFF... not found via pkg-config
  checking for tiffio.h... no
  configure: WARNING: system tiff library not found, will use built-in instead
  checking for expat.h... yes
  checking if expat.h is valid C++ header... yes
  checking for XML_ParserCreate in -lexpat... yes
  checking for GTK+ version...
  checking for pkg-config... (cached) /usr/bin/pkg-config
  checking pkg-config is at least version 0.16... yes
  checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk+-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtk+-3.0' found
  Package gthread-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gthread-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gthread-2.0' found
  no
  *** Could not run GTK+ test program, checking why...
  *** The test program failed to compile or link. See the file config.log for the
  *** exact error that occurred. This usually means GTK+ is incorrectly installed.
  configure: error:
  The development files for GTK+ were not found. For GTK+ 2, please
  ensure that pkg-config is in the path and that gtk+-2.0.pc is
  installed. For GTK+ 1.2 please check that gtk-config is in the path,
  and that the version is 1.2.3 or above. Also check that the
  libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
  --libs' are in the LD_LIBRARY_PATH or equivalent.
  
  Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1471, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "/tmp/pip-install-ygbioixi/wxPython/buildtools/build_wxwidgets.py", line 373, in main
      "Error running configure")
    File "/tmp/pip-install-ygbioixi/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error running configure
  Finished command: build_wx (0m7.941s)
  Finished command: build (0m7.941s)
  Command '"/root/anaconda3/bin/python" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
```

**Comment by Shawn-Zhuang** [comment]
After I run
`conda install wxPython`
（the version is 4.0.4)

and when I import wx
and run 
`wx.__file__`
it shows still `'/root/anaconda3/lib/python3.7/site-packages/vtk/wx/__init__.py'`

**Comment by swt2c** [comment]
There seems to be several problems here.  You seem to be trying to install wxPython via Anaconda *and* pip which could be causing some of your problems.

Installing wxPython via pip (without using a wheel) on Linux requires having a large number of prerequisites installed.  See here for more detailed instructions: https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/

If you would like to install wxPython via pip using a wheel, it is much simpler.  See the list of downloads for Ubuntu 18.04 here:
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/
If you wanted to install wxPython 4.1.0 with Python 3.6 (the System Python on Ubuntu 18.04), you would do:
`pip install -U https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.0-cp36-cp36m-linux_x86_64.whl`
