### ISSUE TITLE
Unexpected type longlong in wxVariant when GetPropertyValues on Debian

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1728]
Hello.
I use Debian x64 10.4, Python 3.7, wxPython 4.1.0.
When trying to save properties from PropertyGrid using:
`pgv = self.property_grid_1.GetPropertyValues(inc_attributes=True)`
I get this error:
```
Traceback (most recent call last):
  File "/home/jure/ThermalView/thermal_view.py", line 1137, in onSaveSet
    pgv = self.property_grid_1.GetPropertyValues(inc_attributes=False)
  File "/usr/local/lib/python3.7/dist-packages/wx/propgrid.py", line 1152, in _PropertyGridInterface_GetPropertyValues
    dict_[name] = getter(p)
TypeError: Unexpected type ("longlong") in wxVariant.
```
`inc_attributes=True` doesn't help either.
I set different types of values in the property grid: 
- wx.propgrid.StringProperty
- wx.propgrid.IntProperty
- wx.propgrid.BoolProperty
- wx.propgrid.EnumProperty

I don't even see the longlong property option.
I can see similar problen in this Issue: https://github.com/wxWidgets/Phoenix/issues/1299
However that guy uses long long value.
Maybe the problem is that everytime I set IntProperty in my code, I should wrap a value in `int(value)` in case it accidently is long long?

**Comment by LumaRay** [comment]
I think I have found a place where property type is changing from Int to LongLong:
`self.property_grid_1.SetPropertyValue(self.S_WINDOW_LEFT, int(wndLeft))`
Even wrapping value in int() doesn't prevent this change.
It seems that SetPropertyValue changes value type to LongLong if it is any number.

**Comment by LumaRay** [comment]
From here: https://docs.wxwidgets.org/3.0/classwx_p_g_property.html#wxIntProperty
"wxIntProperty seamlessly supports 64-bit integers (ie. wxLongLong)."
Well, this is not really convenient, still thinking how to get arond this...

**Comment by LumaRay** [comment]
Well, I think this construction works:
`self.property_grid_1.GetProperty(self.S_WINDOW_LEFT).SetValueFromInt(int(wndLeft))`
This way, the PropertyGrid doesn't "think" it's a longlong anymore...

**Comment by LumaRay** [comment]
Sadly 'self.property_grid_1.GetPropertyValueAsInt' still doesn't work with these values:
```
17:21:52: Операция типа 'Get' не удалась: свойство с меткой 'Позиция Х окна' имеет тип 'longlong', а не 'long'.
```
Which means "Get" unsuccessful as Property(self.S_WINDOW_LEFT) has longlong type....

**Comment by swt2c** [comment]
I think this should be fixed in the latest snapshots.  Can you give them a try?

**Comment by LumaRay** [comment]
Well, for now I changed GetPropertyValueAsInt to GetPropertyValueAsLongLong, so getting as longlong as setting as Int.
If they do fix, I may change my code, so just now I will use this workaround I think.

**Comment by swt2c** [comment]
It would be good to know if the issue you're seeing is the same as the one I fixed, though, so we can make sure it is fixed before the next release.

**Comment by LumaRay** [comment]
No problem, I just need to know what steps to make to use that latest snapshot, can you give me command lines?

**Comment by swt2c** [comment]
Using a snapshot is a little more painful on Linux as you would have to compile it.  Do you see this problem on Windows also, or just on Linux?

Or, if you have a full reproducer program for Linux, I can try it there and make sure it is fixed.

**Comment by LumaRay** [comment]
I have the problem on Linux.
Regarding the reproducer program, I think you can take the code from https://github.com/wxWidgets/Phoenix/issues/1722
And add
```
wndWidth = 100
self.property_grid_1.SetPropertyValue(self.S_WINDOW_WIDTH, int(wndWidth))
```
before
`pgv = self.property_grid_1.GetPropertyValues(inc_attributes=True)`

And just after GetPropertyValues you can add
```
self.property_grid_1.GetProperty(self.S_WINDOW_WIDTH).SetValueFromInt(int(wndWidth))
testInt = self.property_grid_1.GetPropertyValueAsInt(self.S_WINDOW_WIDTH)
```
In this case you will see both problems on v4.1.0.

**Comment by swt2c** [comment]
Yeah, I think this should be fixed in the latest snapshots.

**Comment by LumaRay** [comment]
How can I install them? I have tried to upgrade, but it is still 4.1.0: https://www.screencast.com/t/AvDZ1iDZbUeX

**Comment by swt2c** [comment]
Sorry, you would have to build it from the tarball.  :(  I'll ask Robin why there are no snapshot wheels built for Linux.

**Comment by LumaRay** [comment]
I hear Robin in the comments, maybe he can help now?
