### ISSUE TITLE
typing dot after ctypes.windll in PyShell causes traceback

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1761]
**Description of the problem**:
Type a dot/period after ctypes.windll
This probably is windows specific or might cause issues on other platforms also. Not really sure how this should be handled...

```python
Welcome To PyCrust 0.9.8 - The Flakiest Python Shell
wxPython 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5 Scintilla 3.21
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> windll = ctypes.windll

Traceback (most recent call last):
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\shell.py", line 484, in OnChar
    self.autoCompleteShow(command)
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\shell.py", line 1181, in autoCompleteShow
    list = self.interp.getAutoCompleteList(command,
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\interpreter.py", line 147, in getAutoCompleteList
    l = introspect.getAutoCompleteList(command, self.locals,
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\introspect.py", line 29, in getAutoCompleteList
    attributes = getAttributeNames(obj, includeMagic,
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\introspect.py", line 38, in getAttributeNames
    if not hasattrAlwaysReturnsTrue(obj):
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.0.x-msw-phoenix\wx\py\introspect.py", line 92, in hasattrAlwaysReturnsTrue
    return hasattr(obj, 'bogu5_123_aTTri8ute')
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\testuser\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'bogu5_123_aTTri8ute' (or one of its dependencies). Try using the full path with constructor syntax.

```

**Comment by RobinD42** [comment]
One idea is adding a new `safe_hasattr` function that returns `False` when `hasattr` raises an exception, and then replacing uses of `hasattr` in `introspect.py` with `safe_hasattr`.
