### ISSUE TITLE
AGW AuiNotebook style Bug

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#1795]
**Description of the problem**:
Just revisited this line in my code, and yes, it is still occuring when I tested it again.
http://trac.wxwidgets.org/ticket/16248#no1

<details>
    <summary>Collapsible Content - Click to expand</summary>

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#-Imports.---------------------------------------------------------------------
#--Python Imports.
import os
import sys

#--wxPython Imports.
import wx
import wx.lib.agw.aui as aui
import wx.stc as stc

the_traceback = r"""
# wxPython 4.1.1a1.dev4952+e5021fb5 msw (phoenix) wxWidgets 3.1.5 Scintilla 3.7.2
# Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
# Adding standard border styles to the AuiNotebook style param causes this.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Windows7\Desktop\SourceCoder_Source>py -3 tmpRun.py
4:33:00 AM: Error: Unable to set default locale: 'unsupported locale setting'
Traceback (most recent call last):
  File "tmpRun.py", line 93, in OnInit
    gMainWin = MyFrame(None)
  File "tmpRun.py", line 81, in __init__
    panel = MyPanel(self)
  File "tmpRun.py", line 65, in __init__
    self.nb = MyAuiNotebook(self)
  File "tmpRun.py", line 49, in __init__
    aui.AuiNotebook.__init__(self, parent, id, pos, size, style, agwStyle, name)

  File "C:\Users\Windows7\AppData\Local\Programs\Python\Python38\lib\site-packages\wx-4.1.x-msw\wx\lib\agw\aui\auibook.py", line 3043, in __init__
    wx.Panel.__init__(self, parent, id, pos, size, style|wx.BORDER_NONE|wx.TAB_TRAVERSAL, name=name)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\msw\window.cpp(1566) in wxWindow::MSWGetStyle(): unknown border style
OnInit returned false, exiting...
"""

class MyAuiNotebook(aui.AuiNotebook):
    def __init__(self, parent, id=wx.ID_ANY, pos=wx.DefaultPosition,
                 size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN
                       # | wx.BORDER_SUNKEN # <-- The BUG. unknown border style.
                 ,
                 agwStyle=aui.AUI_NB_DEFAULT_STYLE,
                 name='auinotebook'
                 ):
        aui.AuiNotebook.__init__(self, parent, id, pos, size, style, agwStyle, name)

        for i in range(0, 10):
            s = stc.StyledTextCtrl(self, -1)
            s.SetText('%s' % the_traceback)
            self.AddPage(s, 'page %s' % i)

        self.SetSelection(5)


class MyPanel(wx.Panel):
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        self.nb = MyAuiNotebook(self)
        self.tc = wx.TextCtrl(self, -1, '01234567890' * 3)

        vbSizer = wx.BoxSizer(wx.VERTICAL)
        vbSizer.Add(self.nb, 1, wx.EXPAND | wx.ALL, 5)
        vbSizer.Add(self.tc, 0, wx.EXPAND | wx.ALL, 5)
        self.SetSizer(vbSizer)


class MyFrame(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        panel = MyPanel(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

        self.CreateStatusBar().SetStatusText('wxPython %s' % wx.version())

    def OnDestroy(self, event):
        self.Destroy()

class MyApp(wx.App):
    def OnInit(self):
        self.SetClassName('MyNameApp')
        self.SetAppName('MyNameApp')
        gMainWin = MyFrame(None)
        gMainWin.SetTitle('MyNameFrame')
        self.SetTopWindow(gMainWin)
        gMainWin.Show()
        return True

if __name__ == '__main__':
    gApp = MyApp(redirect=False,
                 filename=None,
                 useBestVisual=False,
                 clearSigInt=True)
    gApp.MainLoop()
```
</details>

**Comment by RobinD42** [comment]
Works for me.
