### ISSUE TITLE
Can not install wxpython with pip

### ISSUE THREAD

**Issue by FelixBenning** [wxWidgets/Phoenix#1967]
**Operating system**: Windows 10
**wxPython version & source**:      4.1.1
**Python version & source**:       3.9

**Description of the problem**:

Installation fails
```shell
Building wheels for collected packages: wxpython
  Building wheel for wxpython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\code\grazer\gui\env\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\felix\\AppData\\Local\\Temp\\pip-install-jm8zis5h\\wxpython_899a3037b7824695939a93b0084cbdcf\\setup.py'"'"'; __file__='"'"'C:\\Users\\felix\\AppData\\Local\\Temp\\pip-install-jm8zis5h\\wxpython_899a3037b7824695939a93b0084cbdcf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\felix\AppData\Local\Temp\pip-wheel-laj00u2w'
       cwd: C:\Users\felix\AppData\Local\Temp\pip-install-jm8zis5h\wxpython_899a3037b7824695939a93b0084cbdcf\
  Complete output (47 lines):
  d:\code\grazer\gui\env\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  Will build using: "d:\code\grazer\gui\env\scripts\python.exe"
  3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
  Python's architecture is 64bit
  cfg.VERSION: 4.1.0

  Running command: build
  Running command: build_wx
  Command '"d:\code\grazer\gui\env\scripts\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "C:\Python39\lib\distutils\msvc9compiler.py", line 371, in initialize

      vc_env = query_vcvarsall(VERSION, plat_spec)

    File "d:\code\grazer\gui\env\lib\site-packages\setuptools\msvc.py", line 139, in msvc9_query_vcvarsall

      return EnvironmentInfo(arch, ver).return_env()

    File "d:\code\grazer\gui\env\lib\site-packages\setuptools\msvc.py", line 1737, in return_env

      [self.VCIncludes,

    File "d:\code\grazer\gui\env\lib\site-packages\setuptools\msvc.py", line 1279, in VCIncludes

      return [join(self.si.VCInstallDir, 'Include'),

    File "d:\code\grazer\gui\env\lib\site-packages\setuptools\msvc.py", line 837, in VCInstallDir

      raise distutils.errors.DistutilsPlatformError(msg)

  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Finished command: build_wx (0.280s)
  Finished command: build (0.284s)
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "d:\code\grazer\gui\env\scripts\python.exe" -u build.py build
  Command '"d:\code\grazer\gui\env\scripts\python.exe" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxpython
```

**Comment by FelixBenning** [comment]
need to perfectly match the installed compiler version for cpp used to compile python
