### ISSUE TITLE
wxPytohn fails in venv

### ISSUE THREAD

**Issue by jakobneufeld** [wxWidgets/Phoenix#2044]
**Operating system**: Nixos/ linux
**wxPython version & source**:          pypi
**Python version & source**:            3.9

**Description of the problem**:

I get this error when I build wxPython in venv.
```

    Running command: build_py
    Checking for /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/bin/waf-2.0.19...
    "/home/drzoidberg/pythonpkgshell/envtest/bin/python" /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/bin/waf-2.0.19 --wx_config=/run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/build/wxbld/gtk3/wx-config --gtk3 --python="/home/drzoidberg/pythonpkgshell/envtest/bin/python" --out=build/waf/3.9/gtk3 configure build
    Setting top to                           : /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799
    Setting out to                           : /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/build/waf/3.9/gtk3
    Checking for 'gcc' (C compiler)          : gcc
    Checking for 'g++' (C++ compiler)        : g++
    Checking for program 'python'            : /home/drzoidberg/pythonpkgshell/envtest/bin/python
    Checking for python version >= 2.7.0     : 3.9.6
    python-config                            : /nix/store/jzaj3bjk5nzpimpsmjl4a2lbf2j76yz8-python3-3.9.6/bin/python3.9-config
    Asking python-config for pyext '--cflags --libs --ldflags' flags : yes
    Testing pyext configuration                                      : Could not build python extensions
    Testing pyext configuration                                      : Could not build python extensions
    The configuration failed
    (complete log in /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/build/waf/3.9/gtk3/config.log)
    Command '"/home/drzoidberg/pythonpkgshell/envtest/bin/python" /run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/bin/waf-2.0.19 --wx_config=/run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/build/wxbld/gtk3/wx-config --gtk3 --python="/home/drzoidberg/pythonpkgshell/envtest/bin/python" --out=build/waf/3.9/gtk3 configure build ' failed with exit code 1.
    Finished command: build_py (0m1.551s)
    Finished command: build (0m2.804s)
    Command '"/home/drzoidberg/pythonpkgshell/envtest/bin/python" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/drzoidberg/pythonpkgshell/envtest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/setup.py'"'"'; __file__='"'"'/run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /run/user/1000/pip-record-zk9roh6i/install-record.txt --single-version-externally-managed --compile --install-headers /home/drzoidberg/pythonpkgshell/envtest/include/site/python3.9/wxPython Check the logs for full command output.


```

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
Can you please attach `/run/user/1000/pip-install-2s0l6qkp/wxpython_864fc262cda54d66b46fb61001cc1799/build/waf/3.9/gtk3/config.log` so we can see what waf doesn't like about your environment?

**Comment by jakobneufeld** [comment]
@swt2c I fixed the issue kind of by adding the open gl headers, but now I get this issue
```
 checking if std::basic_string<wchar_t> works... no
    configure: error: Can't use --enable-std_string without std::wstring or std::basic_string<wchar_t>
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "/run/user/1000/pip-install-cer34i5c/wxpython_9ac138f340274539afe1578ca86161fa/build.py", line 1510, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/run/user/1000/pip-install-cer34i5c/wxpython_9ac138f340274539afe1578ca86161fa/buildtools/build_wxwidgets.py", line 372, in main
        exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
      File "/run/user/1000/pip-install-cer34i5c/wxpython_9ac138f340274539afe1578ca86161fa/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m4.448s)
    Finished command: build (0m4.448s)
    Command '"/home/drzoidberg/pythonpkgshell/envtest/bin/python" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/drzoidberg/pythonpkgshell/envtest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/run/user/1000/pip-install-cer34i5c/wxpython_9ac138f340274539afe1578ca86161fa/setup.py'"'"'; __file__='"'"'/run/user/1000/pip-install-cer34i5c/wxpython_9ac138f340274539afe1578ca86161fa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /run/user/1000/pip-record-omb22_2y/install-record.txt --single-version-externally-managed --compile --install-headers /home/drzoidberg/pythonpkgshell/envtest/include/site/python3.9/wxPython Check the logs for full command output.
```

**Comment by jakobneufeld** [comment]
@swt2c Thanks so much for replying anyway!

**Comment by jakobneufeld** [comment]
Honestly I did not expect a response, because most package maintainers hate NixOS users :laughing:

**Comment by swt2c** [comment]
> Honestly I did not expect a response, because most package maintainers hate NixOS users laughing

I try not to hate anybody.  :-)  I'm even more confused now about the error as it seems to be saying that your system doesn't support std::wstring.
