### ISSUE TITLE
unhashable type: 'GridCellCoords' in py3

### ISSUE THREAD

**Issue by dragonyanglong** [wxWidgets/Phoenix#2046]
**Operating system**: Mac OS 10.13.6
**wxPython version & source**: wxpython                  4.0.4            py37hebc47a7_0    anaconda         
**Python version & source**:   anaconda Python 3.7.9         

**Description of the problem**: 

When changing from py2.7 to py3, the grid.GridCellCoords functions doesn't work properly.

When use keyboard `shift` to select multi-cells, it works as normal. But once use `control` to select multi-cells, it raises the error as:

```
Traceback (most recent call last):
  File "/home/phaseconfigurepanel.py", line 453, in onEditorShown
    self._selectedCells = gridutils.getSelectedCells(self.gridAtoms)
  File "/home/envs/pdfgui_py37_test/lib/python3.7/site-packages/diffpy.utils-3.0.0-py3.7.egg/diffpy/utils/wx/gridutils.py", line 78, in getSelectedCells
    rcset.update(grid.GetSelectedCells())
TypeError: unhashable type: 'GridCellCoords'
```

The codes that are related with this issue is also attached as below, and the last two line is where the function breaks.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx

def getSelectionRows(grid):
    """Indices of the rows that have any cell selected.
    """
    rows = grid.GetNumberRows()
    rset = set()
    if grid.GetSelectedCols():
        rset.update(range(rows))
    rset.update(grid.GetSelectedRows())
    for r, c in grid.GetSelectedCells():
        rset.add(r)
    blocks = zip(grid.GetSelectionBlockTopLeft(),
            grid.GetSelectionBlockBottomRight())
    for tl, br in blocks:
        rset.update(range(tl[0], br[0] + 1))
    rv = sorted(rset)
    return rv


def getSelectionColumns(grid):
    """Indices of columns that have any cell selected.
    """
    cols = grid.GetNumberCols()
    cset = set()
    if grid.GetSelectedRows():
        cset.update(range(cols))
    cset.update(grid.GetSelectedCols())
    for r, c in grid.GetSelectedCells():
        cset.add(c)
    blocks = zip(grid.GetSelectionBlockTopLeft(),
            grid.GetSelectionBlockBottomRight())
    for tl, br in blocks:
        cset.update(range(tl[1], br[1] + 1))
    rv = sorted(cset)
    return rv


def getSelectedCells(grid):
    """Get list of (row, col) pairs of all selected cells.
    Unlike grid.GetSelectedCells this returns them all no matter
    how they were selected.
    """
    rows = grid.GetNumberRows()
    cols = grid.GetNumberCols()
    allrows = range(rows)
    allcols = range(cols)
    rcset = set()
    for r in grid.GetSelectedRows():
        rcset.update(zip(cols * [r], allcols))
    for c in grid.GetSelectedCols():
        rcset.update(zip(allrows, rows * [c]))
    blocks = zip(grid.GetSelectionBlockTopLeft(),
            grid.GetSelectionBlockBottomRight())
    for tl, br in blocks:
        brows = range(tl[0], br[0] + 1)
        bcols = range(tl[1], br[1] + 1)
        rcset.update((r, c) for r in brows for c in bcols)
    rcset.update(grid.GetSelectedCells())
    rv = sorted(rcset)
    return rv
```
</details>

**Comment by swt2c** [comment]
Can you please provide a small, self-contained, complete example that reproduces the problem?

**Comment by dragonyanglong** [comment]
Dear @swt2c , I added the complete example code into the `code example`. Does it provide enough info for you?

Thanks so much for your help.

**Comment by swt2c** [comment]
That's more helpful, but it would be even more helpful if it was a runnable example, ie, I could paste into a file and run it and it would reproduce the problem.

**Comment by dragonyanglong** [comment]
@swt2c , sure I will try that, but since the original project is pretty large, it is not quite straightforward to cut it into a small runnable example.

Meanwhile, I notice that someone posted a similar issue about unhashable thing in py3 at #319. Could you please help take a quick look and any insights on the code example (though not runnable yet)?

**Comment by swt2c** [comment]
Can you also please try a newer version of wxPython (at least version 4.0.7)?  This example works fine for me on wxPython 4.0.7.

```
import wx
import wx.grid

app = wx.App()
grid = wx.grid.Grid()
rcset = set()
rcset.update(grid.GetSelectedCells())
```

**Comment by dragonyanglong** [comment]
@swt2c I updated wxpython to 4.0.7 via pip, still didn't work. Did you use python 3.7.9?

BTW, the newest version of wxpython at conda seems to be 4.0.4, any newer version available at conda?

**Comment by swt2c** [comment]
> @swt2c I updated wxpython to 4.0.7 via pip, still didn't work. Did you use python 3.7.9?

No, I used Python 3.8.10.  Does my simple example fail for you in your environment?

> BTW, the newest version of wxpython at conda seems to be 4.0.4, any newer version available at conda?

You would have to ask the conda folks about that.  The wxPython maintainers don't maintain the conda packages.
