### ISSUE TITLE
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call _April2022

### ISSUE THREAD

**Issue by Nygration** [wxWidgets/Phoenix#2135]
**Specs**:
OS: Ubuntu 20.04 (yes I read the page about ubuntu builds)
wxpython v4.1.1, installed dependencies as required by pyPENELOPE
Python v3.10.4 , via anaconda and forcing it up to 3.10

**Description of the problem**:
Trying to use pyPENELOPE, used futurize to ready the code for python3.
In the main.py its trying to call wx.ToolBar.AddTool  [documentation here](http://pypenelope.sourceforge.net/code/penelopetools/gui/main.html)
`wx.ToolBar.AddTool` is called can provided `(1,label,bmp,shortHelp=label, clientData=program)`

Where its called at the beginning of main.py
```
class Main(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, title="pyPENELOPE")

        # Variables
        self.controller = SimulationController(self)

        # Controls
        self._menubar = MenuBar(self)
        self.SetMenuBar(self._menubar)
        self.controller.register_hook(self._menubar)

        self._toolbar = ToolBar(self)
        self.SetToolBar(self._toolbar)
        self.controller.register_hook(self._toolbar)
```
Where its called in the ToolBar.init
```
class ToolBar(wx.ToolBar):
    def __init__(self, parent):
        wx.ToolBar.__init__(self, parent)

        self._program_tools = []
        for program in PROGRAMS:
            label = 'New %s simulation' % program.NAME
            bmp = wx.Bitmap(program.ICON)

            tool = self.AddTool(1, label, bmp, shortHelp=label, clientData=program)
            parent.Bind(wx.EVT_TOOL, parent.on_new, tool)
            parent.Bind(wx.EVT_TOOL_RCLICKED, parent.on_new_rclick, tool)

            self._program_tools.append(tool)
```
The Error Message 
```
Traceback (most recent call last):
  File "/home/cnygren@Astin.Local/./pyPENELOPE_new/penelopetools/gui/main.py", line 881, in <module>
    run()
  File "/home/cnygren@Astin.Local/./pyPENELOPE_new/penelopetools/gui/main.py", line 868, in run
    mainframe = Main(parent=None)
  File "/home/cnygren@Astin.Local/./pyPENELOPE_new/penelopetools/gui/main.py", line 521, in __init__
    self._toolbar = ToolBar(self)
  File "/home/cnygren@Astin.Local/./pyPENELOPE_new/penelopetools/gui/main.py", line 229, in __init__
    tool = self.AddTool(1, label, bmp, shortHelp=label, clientData=program)
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: 'clientData' is not a valid keyword argument
  overload 3: 'shortHelp' is not a valid keyword argument
```
Its unclear to me how an int is unexpected for toolid, or how clientData and shortHelp are not valid keywords.

**Comment by swt2c** [comment]
Please see the documentation for `wx.ToolBar.AddTool()`: https://docs.wxpython.org/wx.ToolBar.html#wx.ToolBar.AddTool

If you want to use the overload that takes `clientData`, `bmpDisabled` is a required argument that you do not appear to be passing.
