### ISSUE TITLE
GenericButton does not work

### ISSUE THREAD

**Issue by rscottha** [wxWidgets/Phoenix#2149]
**Operating system**:Linux (Manjaro)
**wxPython version & source**:   4.0.7.post2  pacman       
**Python version & source**:    3.10.4 distro        

**Description of the problem**: GenericButtons fails in wxDemo and there is a similar fail in wxGlade. Standard out from wxDemo is:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/wx/lib/buttons.py", line 492, in OnPaint
    self.DrawLabel(dc, width, height)
  File "/usr/lib/python3.10/site-packages/wx/lib/buttons.py", line 452, in DrawLabel
    dc.DrawText(label, (width-tw)/2+dx, (height-th)/2+dy)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by swt2c** [comment]
This is due to a change in Python 3.10.  It was fixed a while ago: https://github.com/wxWidgets/Phoenix/commit/173d0796810bb65de9bdfdc6941d24a04628f6c2

If you are using a distribution package, you could ask them to pick up that patch.
