### ISSUE TITLE
Can not import wx (4.1.2a1.dev5423+9347915e) module on macOS 

### ISSUE THREAD

**Issue by BrendanSimon** [wxWidgets/Phoenix#2178]
Can not import wx module on macOS

**Operating system**: macOS Monterey 12.4
**wxPython version**:  4.1.2a1.dev5423+9347915e
**Python version**:  3.9.13

**Description of the problem**:

<details>
  <summary>REPL output (click to expand)</summary>

```
venv_py3.9) ➜  wxPhoenix git:(master) python
Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brendan/venv_py3.9/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/Users/brendan/venv_py3.9/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dynamic module does not define module export function (PyInit__core)
```

```
venv_py3.9) ➜  wxPhoenix git:(master) pip list
Package        Version
-------------- ------------------------
numpy          1.22.3
Pillow         9.1.1
pip            22.1.2
psutil         5.9.0
setuptools     58.1.0
six            1.16.0
wheel          0.37.1
wxPython       4.1.2a1.dev5423+9347915e
```

```
(venv_py3.9) ➜  wxPhoenix git:(master) uname -a
Darwin 10.0.0.115 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

</details>

**Comment by RobinD42** [comment]
This should be fixed in 502d835401f80028bd1593b41f09700a4b3b1866. Please try again after the next snapshot build.
