### ISSUE TITLE
sipbuild broken with SIP 6.5.x

### ISSUE THREAD

**Issue by StefanBruens** [wxWidgets/Phoenix#2229]
SIP 6.5 should be working according to:

https://github.com/wxWidgets/Phoenix/blob/e220dab24092d91dfa0fecfa5e98e989c9f9d3d0/build.py#L1289

Unfortunately, sipbuild from 6.5 has a bug fixed in 6.6:

https://www.riverbankcomputing.com/hg/sip/diff/0da96769835f/sipbuild/bindings.py
```
-            generateExtracts(pt, extracts)
+            generateExtracts(pt, self.generate_extracts)
```

causing build.py to error out:
```
[  292s] + python3.8 build.py sip --use_syswx --gtk3 -v
[  294s] These bindings will be built: _core.
[  294s] Generating the _core bindings...
[  300s] sip-build: An internal error occurred...
[  300s] Traceback (most recent call last):
[  300s]   File "/usr/bin/sip-build", line 33, in <module>
[  300s]     sys.exit(load_entry_point('sip==6.5.1', 'console_scripts', 'sip-build')())
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/tools/build.py", line 37, in main
[  300s]     handle_exception(e)
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/exceptions.py", line 81, in handle_exception
[  300s]     raise e
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/tools/build.py", line 34, in main
[  300s]     project.build()
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/project.py", line 249, in build
[  300s]     self.builder.build()
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/builder.py", line 48, in build
[  300s]     self._generate_bindings()
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/builder.py", line 275, in _generate_bindings
[  300s]     buildable = bindings.generate()
[  300s]   File "/usr/lib64/python3.8/site-packages/sipbuild/bindings.py", line 187, in generate
[  300s]     generateExtracts(pt, extracts)
[  300s] NameError: name 'extracts' is not defined
```

**Comment by swt2c** [comment]
Yeah, that's a lie in build.py.  sip 6.6.2+ is required.

**Comment by swt2c** [comment]
See https://github.com/wxWidgets/Phoenix/commit/969c2d163564e9fef569ee05b748a35fe9fca4e9
