### ISSUE TITLE
Missing NumPy package reference when using "float_" in wx\lib\floatcanvas\FloatCanvas.py

### ISSUE THREAD

**Issue by pchemguy** [wxWidgets/Phoenix#2242]
**Windows 10**:
**wxPython 4.2.0 pypi**:          
**Python 3.10.5 anaconda**:            

**Description of the problem**:

An attempt to execute "samples\floatcanvas\Animation.py" (as well as a number of other sample scripts) causes an error

```
B:\wxPython-demo-4.2.0\samples\floatcanvas>python Animation.py
4.2.0
using installed version: 0.9.18
Adding Points to Foreground
Traceback (most recent call last):
  File "B:\wxPython-demo-4.2.0\samples\floatcanvas\Animation.py", line 243, in OnInit
    frame = DrawFrame(None, -1, "Simple Drawing Window",wx.DefaultPosition, (700,700) )
  File "B:\wxPython-demo-4.2.0\samples\floatcanvas\Animation.py", line 101, in __init__
    self.DrawTest(None)
  File "B:\wxPython-demo-4.2.0\samples\floatcanvas\Animation.py", line 176, in DrawTest
    Canvas.ZoomToBB()
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FloatCanvas.py", line 782, in ZoomToBB
    (BoundingBox[0,1]+BoundingBox[1,1])/2 ),float_)
NameError: name 'float_' is not defined. Did you mean: 'float'?
OnInit returned false, exiting...
```

**Comment by pchemguy** [comment]
Push an additional commit fixing *xrange* use in "samples\floatcanvas\DrawBot.py" (replaced with six.moves.xrange for Python 2/3 compatibility).

**Comment by pchemguy** [comment]
A third commit adds explicit typecasting in wx\lib\floatcanvas\FCObjects.py. Without this fix, an attempt to execute samples\floatcanvas\ScaledBitmap2Demo.py throws an error:

```
B:\Phoenix\samples\floatcanvas>python ScaledBitmap2Demo.py
Traceback (most recent call last):
  File "B:\Phoenix\samples\floatcanvas\ScaledBitmap2Demo.py", line 69, in <module>
    F = DrawFrame(None, title="FloatCanvas Demo App", size=(700,700) )
  File "B:\Phoenix\samples\floatcanvas\ScaledBitmap2Demo.py", line 58, in __init__
    Canvas.ZoomToBB()
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FloatCanvas.py", line 804, in ZoomToBB
    self.SetToNewScale(DrawFlag=DrawFlag)
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FloatCanvas.py", line 823, in SetToNewScale
    self.Draw()
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FloatCanvas.py", line 628, in Draw
    self._DrawObjects(dc, self._DrawList, ScreenDC, self.ViewPortBB, HTdc)
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FloatCanvas.py", line 988, in _DrawObjects
    Object._Draw(dc, WorldToPixel, ScaleWorldToPixel, HTdc)
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FCObjects.py", line 2366, in _Draw
    self._DrawEntireBitmap(dc , WorldToPixel, ScaleWorldToPixel, HTdc)
  File "G:\ProgramsMisc\Anaconda\envs\Anaconda_MSRU_C-dev-Py_Cona\lib\site-packages\wx\lib\floatcanvas\FCObjects.py", line 2277, in _DrawEntireBitmap
    Img = self.Image.Scale(W, H)
TypeError: Image.Scale(): argument 1 has unexpected type 'numpy.float64'
```
