### ISSUE TITLE
The demo.py does not work

### ISSUE THREAD

**Issue by gcailly** [wxWidgets/Phoenix#2307]
**Operating system**: Windows 10
**wxPython version & source**: 4.2.0
**Python version & source**: 3.10

**Description of the problem**:

When I launch the demo :

```
Traceback (most recent call last):
  File "C:\Users\Gautier\Desktop\Phoenix-master\demo\demo.py", line 3, in <module>
    import Main
  File "C:\Users\Gautier\Desktop\Phoenix-master\demo\Main.py", line 75, in <module>
    import version
ModuleNotFoundError: No module named 'version'
```

**Comment by swt2c** [comment]
Yes, that file is generated as part of the build process and is not stored in the git repo.
