### ISSUE TITLE
ModuleNotFoundError: No module named 'run'

### ISSUE THREAD

**Issue by DestoGit** [wxWidgets/Phoenix#2312]
**Operating system**: Windows 10
**wxPython version & source**:      [wxPython-4.2.1a1.dev5539+906adf71-cp39-cp39-win_amd64.whl](https://wxpython.org/Phoenix/snapshot-builds/) 
**Python version & source**:       3.9.12 stock     

**Description of the problem**:

I'm trying to run the from WrapSizer.py demo
[WrapSizer.py](https://github.com/wxWidgets/Phoenix/blob/master/demo/WrapSizer.py)

but get this error:

```
Traceback (most recent call last):
  File "C:\mywxpython\gui001.py", line 94, in <module>
    import run
ModuleNotFoundError: No module named 'run'
```

I tried installing run with

`pip install run` 

but get this other error:

```
C:\Python39\Lib>pip install run
Collecting run
  Downloading run-0.2.tar.gz (3.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-d6kdsxfv\run_c51a30ade0af452385415a35a88289e5\setup.py", line 12, in <module>
          long_description=file('README').read(),
      NameError: name 'file' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Is there a working WrapSizer.py code demo for python 3x?
Thanks for your next info.

**Comment by swt2c** [comment]
This is the run that you need: https://github.com/wxWidgets/Phoenix/blob/master/demo/run.py

I'd suggest downloading the demos from https://extras.wxpython.org/wxPython4/extras/4.2.0/wxPython-demo-4.2.0.tar.gz

**Comment by DestoGit** [comment]
Thanks a lot for the reply and demo link!
The error is fixed however I'm getting this prompt now:
```
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
wx.version: 4.2.0 msw (phoenix) wxWidgets 3.2.0
Please specify a demo module name on the command-line
[Finished in 364ms]
```
Any idea how I should specify the demo module name? I've done a quick google search but not getting info on this.
Thanks!

**Comment by swt2c** [comment]
What is gui001.py?  Try WrapSizer.py.

**Comment by DestoGit** [comment]
Great thanks!

I was running it from another file that was the issue.

Fixed it by copy-paste the 

[wxPython-demo-4.2.0](https://extras.wxpython.org/wxPython4/extras/4.2.0/wxPython-demo-4.2.0.tar.gz) 

content into my 
`C:\mywxpython\wxPython-demo-4.2.0\demo` 

folder.

Then I ran the WrapSizer.py in Sublime Text/ Terminus from
`C:\mywxpython\wxPython-demo-4.2.0\demo\WrapSizer.py`

But got this error:

Microsoft Windows [Version 10.0.19044.2251]                                                                                                                               
(c) Microsoft Corporation. All rights reserved.                                                                                                                           
                                                                                                                                                                          
```
C:\mywxpython\wxPython-demo-4.2.0\demo>python WrapSizer.py                                                                                                                
Traceback (most recent call last):                                                                                                                                        
  File "C:\mywxpython\wxPython-demo-4.2.0\demo\WrapSizer.py", line 113, in <module>                                                                                       
    import run                                                                                                                                                            
  File "C:\mywxpython\wxPython-demo-4.2.0\demo\run.py", line 21, in <module>                                                                                              
    import wx.lib.inspection                                                                                                                                              
  File "C:\Python39\lib\site-packages\wx\lib\inspection.py", line 27, in <module>                                                                                         
    import wx.py                                                                                                                                                          
  File "C:\Python39\lib\site-packages\wx\py\__init__.py", line 5, in <module>                                                                                             
    from . import buffer                                                                                                                                                  
  File "C:\Python39\lib\site-packages\wx\py\buffer.py", line 5, in <module>                                                                                               
    from .interpreter import Interpreter                                                                                                                                  
  File "C:\Python39\lib\site-packages\wx\py\interpreter.py", line 11, in <module>                                                                                         
    from . import introspect                                                                                                                                              
  File "C:\Python39\lib\site-packages\wx\py\introspect.py", line 11, in <module>                                                                                          
    from six import BytesIO, PY3, string_types                                                                                                                            
ModuleNotFoundError: No module named 'six'
```                                                                                                                                

which I fixed then py

`pip install six`

from inside my

`C:\Python39\Lib`

folder.

Now it's working:

![WrapSizer py](https://user-images.githubusercontent.com/118631277/204663963-12d456e9-a39d-4165-89e7-95d50401360b.png)
