### ISSUE TITLE
etgtools.DoxyXMLError: Unable to find xml file for ITEM: wxTextCtrl

### ISSUE THREAD

**Issue by sl1pkn07** [wxWidgets/Phoenix#2315]
**Operating system**: archlinux
**wxPython version & source**:          4.0.2 selfbuild from tarball
**Python version & source**:            3.10.8 from distro packages

**Description of the problem**:

when try to build with this command:

~~~
  DOXYGEN=/usr/bin/doxygen \
  SIP=/usr/bin/sip \
  WAF=/usr/bin/waf \
  WX_SKIP_DOXYGEN_VERSION_CHECK=1 \
  python -u build.py dox
  python -u build.py etg --nodoc
  python -u build.py sip 
  python -u build.py build --use_syswx --release
~~~

i get:

~~~
Running command: etg
"/usr/bin/python" etg/_core.py --sip --nodoc
"/usr/bin/python" etg/_xrc.py --sip --nodoc
"/usr/bin/python" etg/_stc.py --sip --nodoc
Unable to find xml file for ITEM: wxTextCtrl
Tried: /tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/ext/wxWidgets/docs/doxygen/out/xml/classwx_text_ctrl.xml
       /tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/ext/wxWidgets/docs/doxygen/out/xml/structwx_text_ctrl.xml
       /tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/ext/wxWidgets/docs/doxygen/out/xml/wxTextCtrl
Traceback (most recent call last):
  File "/tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/etg/_stc.py", line 243, in <module>
    run()
  File "/tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/etg/_stc.py", line 151, in run
    mod = textctrl.parseAndTweakModule()
  File "/tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/etg/textctrl.py", line 32, in parseAndTweakModule
    etgtools.parseDoxyXML(module, ITEMS)
  File "/tmp/makepkg/python-wxpython-light/src/wxPython-4.0.2/etgtools/__init__.py", line 82, in parseDoxyXML
    raise DoxyXMLError(msg)
etgtools.DoxyXMLError: Unable to find xml file for ITEM: wxTextCtrl
Command '"/usr/bin/python" etg/_stc.py --sip --nodoc' failed with exit code 1.
Finished command: etg (0m1.757s)
~~~

my system-wide wxwidgets (gtk3) 3.2.1 is builded without mediacontol

**Comment by swt2c** [comment]
wxPython 4.0.2 isn't compatible with wxWidgets 3.2.1.  If you really need such an old version, you need to use wxWidgets 3.0.x.  However, I would strongly advise you to use wxPython 4.2.0.

**Comment by sl1pkn07** [comment]
doh. you are right. my fail to download the right version

but with 4.2.0:

~~~
Running command: sip
sip-build --no-compile
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.7.5', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
Command 'sip-build --no-compile' failed with exit code 1.
Finished command: sip (0.97s)
~~~

sip 6.7.5

greetings
