### ISSUE TITLE
No module named wx, installation failed

### ISSUE THREAD

**Issue by christian179717** [wxWidgets/Phoenix#2328]
**Operating system**:  Linux Mint 21.1
**wxPython version & source**: none
**Python version & source**: 3.10; apt
**Description of the problem**:

I need the module wx for another program. (`ImportError: No module named wx`)
I've tried to install it in different ways but every attempt failed:
1. from https://wxpython.org/pages/downloads/index.html
```
pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04
Requirement already satisfied: wxPython in /usr/lib/python3/dist-packages (4.0.7)
DEPRECATION: The HTML index page being used (https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9jmiug73/wxpython_2accaaed8cbe41fd95b62c96fceb12e0/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-9jmiug73/wxpython_2accaaed8cbe41fd95b62c96fceb12e0/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/home/philipp/.local/lib/python3.10/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/home/philipp/.local/lib/python3.10/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
2. from https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html
```
user@user-Latitude-E5550:~/Programme/Python/WX$ python3 -m venv builder_py 
source builder_py/bin/activate

which python
which pip
/home/user/Programme/Python/WX/builder_py/bin/python
/home/user/Programme/Python/WX/builder_py/bin/pip
(builder_py) user@user-Latitude-E5550:~/Programme/Python/WX$ pip install -U pip
pip install -U six wheel setuptools
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: pip in ./builder_py/lib/python3.10/site-packages (21.2.4)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/six/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/six/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/six/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/six/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/six/
Could not fetch URL https://pypi.org/simple/six/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/six/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement six (from versions: none)
ERROR: No matching distribution found for six
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
(builder_py) user@user-Latitude-E5550:~/Programme/Python/WX$ pip download wxPython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wxpython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wxpython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wxpython/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wxpython/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/wxpython/
Could not fetch URL https://pypi.org/simple/wxpython/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/wxpython/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement wxPython (from versions: none)
ERROR: No matching distribution found for wxPython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```
Do you know why all attempts failed?

**Comment by swt2c** [comment]
In the first case, you need to `pip install attrdict3`.  In the second case, <shrug> that's really strange as you don't seem to have SSL support from your Python installation?

**Comment by christian179717** [comment]
Something different happened now:
```
pip download wxPython
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... done
Collecting pillow
  Downloading Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 6.2 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting numpy
  Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 6.7 MB/s eta 0:00:00
Saved ./wxPython-4.2.0.tar.gz
Saved ./numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Saved ./Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl
Saved ./six-1.16.0-py2.py3-none-any.whl
Successfully downloaded wxPython numpy pillow six
```
But if I trie running the program it still doesn't work

**Comment by mesalu** [comment]
If I remember correctly, `pip download` merely acquires the packages, placing them in the current directory instead of actually installing them into your python environment. (In this case it downloaded wxPython's `.tar.gz` bundle and numpy, pillow, and six's `.whl` files)

You likely want to use `pip install`. Based on prior comments, something like this:
```
pip install --upgrade attrdict3
pip install wxpython
```

**Comment by christian179717** [comment]
Terminal output:
```
efaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: attrdict3 in ./.local/lib/python3.10/site-packages (2.0.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from attrdict3) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wxpython in /usr/lib/python3/dist-packages (4.0.7)
```
Still does not work.

**Comment by mesalu** [comment]
Well, it looks like my knowledge of the build sequence is a bit out dated. 

What you'll want to do is step 6 [here](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/) (In the same directory that you had previously `pip download`ed wxPython.)

That said, the errors above and prior indicate that something is off with your environment. I'd suggest identifying and addressing the missing libraries & permissions before trying to build & install wx.

**Comment by christian179717** [comment]
Where could I ask for that?

**Comment by christian179717** [comment]
I've already have Python 3.10.1
(
```
python3 --version
Python 3.10.1
```
)

**Comment by christian179717** [comment]
```
whereis python
python:
```

**Comment by christian179717** [comment]
![grafik](https://user-images.githubusercontent.com/89655752/212372456-483051ae-3b2b-4b3c-b45d-c319f50ddab9.png)

**Comment by christian179717** [comment]
![grafik](https://user-images.githubusercontent.com/89655752/212490963-8410b6e6-eda4-40e6-a868-948a86b9e8c9.png)
I can't find it there, even after reboot.

**Comment by christian179717** [comment]
Apt

**Comment by christian179717** [comment]
Now it's in /usr/local/bin but with
```
pip install --upgrade attrdict3
pip install wxpython
```
or
```
pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython
```
it still does not work.

**Comment by christian179717** [comment]
> also use pip3 instead of pip
`Running setup.py install for wxpython ...`
is shown for almost two minutes, will there come something different?
> which ide youre using ?
It isn't for a self written program. I'm running it via a terminal.

**Comment by christian179717** [comment]
```
WARNING: The scripts f2py, f2py3 and f2py3.11 are installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  DEPRECATION: wxpython is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
Would that be a problem or can I still install it?

**Comment by christian179717** [comment]
> its going to take a while to build idk why but yea it should work now once installed

It's still not installed, do you have a benchmark how much time it needs?


> its fine you can add it to path if you know how,

I've no idea how doing it.

> also its good to use a venv env for installing pip packages if you know what that means

Also there, I don't know, what it means.

**Comment by christian179717** [comment]
Thank you very much, everything is fine now and it works.
