### ISSUE TITLE
Wxdemo for the snapshot-builds fails to download files.

### ISSUE THREAD

**Issue by komoto48g** [wxWidgets/Phoenix#2341]
**Operating system**: Windows 10
**wxPython version & source**: 4.2.1a1.dev5545+a3b6cfec
**Python version & source**: 3.10.8

**Description of the problem**:
When executing wxdemo for the snapshot-builds, it tries to download the tar.gz file but fails.
It seems to be referencing the wrong URL: `"https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz"`

<details>
  <summary>Shell output (click to expand)</summary>

```python
>wxdemo
sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] ['C:\\Python310\\Scripts\\wxdemo.exe']
Launch Demo for wxPython V4.2.1a1.dev5545+a3b6cfec
Looking for wxPython-demo-4.2.1a1.dev5545+a3b6cfec at C:\Users\omoto\AppData\Local\wxPython
Looking for cached C:\Users\omoto\AppData\Local\wxPython\wxDocsDemoCache\4.2.1a1.dev5545+a3b6cfec\wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
Trying:
   wget https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz -O C:\Users\omoto\AppData\Local\wxPython\wxDocsDemoCache\4.2.1a1.dev5545+a3b6cfec\wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz --no-check-certificate
--2023-02-05 19:50:24--  https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
Resolving extras.wxpython.org... 173.212.231.191
Connecting to extras.wxpython.org|173.212.231.191|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
wget did not work or not installed - trying urllib
Trying to Download via urllib from:
   https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
Error: HTTP Error 404: Not Found
Trying to use pip to download From:
   https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz To:
   C:\Users\omoto\AppData\Local\wxPython\wxDocsDemoCache\4.2.1a1.dev5545+a3b6cfec\wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
Running pip pip download https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz --dest C:\Users\omoto\AppData\Local\wxPython\wxDocsDemoCache\4.2.1a1.dev5545+a3b6cfec --no-deps --exists-action i --trusted-host https://extras.wxpython.org

Abusing pip so expect possible error(s) in the next few lines.
Collecting https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
  File was already downloaded c:\users\omoto\appdata\local\wxpython\wxdocsdemocache\4.2.1a1.dev5545+a3b6cfec\wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Python310\lib\site-packages\pip\_internal\commands\download.py", line 138, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 176, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "C:\Python310\lib\site-packages\pip\_internal\utils\unpacking.py", line 246, in unpack_file
    untar_file(filename, location)
  File "C:\Python310\lib\site-packages\pip\_internal\utils\unpacking.py", line 173, in untar_file
    tar = tarfile.open(filename, mode, encoding="utf-8")
  File "C:\Python310\lib\tarfile.py", line 1652, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\Python310\lib\tarfile.py", line 1705, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "C:\Python310\lib\tarfile.py", line 1682, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Python310\lib\tarfile.py", line 1542, in __init__
    self.firstmember = self.next()
  File "C:\Python310\lib\tarfile.py", line 2365, in next
    raise ReadError("empty file") from None
tarfile.ReadError: empty file
Download via pip may have Failed!
Command '['pip', 'download', 'https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec/wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz', '--dest', 'C:\\Users\\omoto\\AppData\\Local\\wxPython\\wxDocsDemoCache\\4.2.1a1.dev5545+a3b6cfec', '--no-deps', '--exists-action', 'i', '--trusted-host', 'https://extras.wxpython.org']' returned non-zero exit status 2.


ERROR in Web Access! - You may be behind a firewall!
----------------------------------------------------
You should be able to bybass this by using a browser to download:
        wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz
from:   https://extras.wxpython.org/wxPython4/extras/4.2.1a1.dev5545+a3b6cfec
then copying the download file to:
        C:\Users\omoto\AppData\Local\wxPython\wxDocsDemoCache\4.2.1a1.dev5545+a3b6cfec\wxPython-demo-4.2.1a1.dev5545+a3b6cfec.tar.gz

Closing Launcher App!
Unable to find and start the wxPython Demo!
```
</details>

**Comment by komoto48g** [comment]
Though the problem is due to the wrong URL, I also noticed that the demo files for `4.2.1a1.dev5545` is missing in "https://wxpython.org/Phoenix/snapshot-builds/".

**Comment by abulka** [comment]
Also the demo fails to download because `TypeError: ProgressDialog(): argument 'maximum' has unexpected type 'float'`

Repro: Using python 3.10 on mac command line, type `wxdemo`.

**Comment by komoto48g** [comment]
Hi @abulka, 
The issue you mentioned might be #2308, which has been fixed and merged into the snapshot `4.2.1a1.dev5545+a3b6cfec`.
