### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by rokejulianlockhart** [wxWidgets/Phoenix#2386]
**Operating system**:
```pwsh
PS /home/rokejulianlockhart> uname -a                    
Linux RQN6C6 6.2.12-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr 20 11:01:10 UTC 2023 (eb3255d) x86_64 x86_64 x86_64 GNU/Linux
```

**wxPython version & source**:
```pwsh
PS /home/rokejulianlockhart> pip3 show wxPython
WARNING: Package(s) not found: wxPython
NativeCommandExitException: Program "pip3" ended with non-zero exit code: 1.
```

**Python version & source**:

```pwsh
PS /home/rokejulianlockhart> cnf python3        
                         
Program 'python3' is present in package 'python310-base', which is installed on your system.

Absolute path to 'python3' is '/usr/bin/python3'. Please check your $PATH variable to see whether it contains the mentioned path.

PS /home/rokejulianlockhart> zypper info python310-base
Repository 'Packman Repository' is out-of-date. You can run 'zypper refresh' as root to update it.
Repository 'Packman' is out-of-date. You can run 'zypper refresh' as root to update it.
Loading repository data...
Reading installed packages...


Information for package python310-base:
---------------------------------------
Repository     : Main Repository (OSS)
Name           : python310-base
Version        : 3.10.10-2.2
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 33.2 MiB
Installed      : Yes
Status         : up-to-date
Source package : python310-core-3.10.10-2.2.src
Upstream URL   : https://www.python.org/
Summary        : Python 3 Interpreter and Stdlib Core
Description    : 
    Python is an interpreted, object-oriented programming language, and is
    often compared to Tcl, Perl, Scheme, or Java.  You can find an overview
    of Python in the documentation and tutorials included in the python-doc
    package.

    This package contains the interpreter core and most commonly used modules
    from the standard library. This is sufficient for many usecases, but it
    excludes components that depend on external libraries, most notably XML,
    database and UI toolkits support.

PS /home/rokejulianlockhart>
```

**Description of the problem**:

```pwsh
PS /home/rokejulianlockhart> pip3 install wxPython            
Defaulting to user installation because normal site-packages is not writeable
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b24m_lxm/wxpython_14ce4cab14954214823f5e9153a5ceae/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-b24m_lxm/wxpython_14ce4cab14954214823f5e9153a5ceae/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
NativeCommandExitException: Program "pip3" ended with non-zero exit code: 1.
PS /home/rokejulianlockhart>
```

**Comment by monkut** [comment]
installing attrdict3 before trying to install wxpython will get you a step further...

but I'm still stuck with it failing at:

```

The configuration failed
      (complete log in /tmp/pip-install-pi89eq5w/wxpython_1ccbd10a899947f5917b5f032a7572e0/build/waf/3.9/gtk3/config.log)
...

ERROR: Failed building wheel for wxpython
```

And unfortunately, the config.log file is cleaned up after install attempt.

**Comment by swt2c** [comment]
Unfortunately, we can't help much without being able to see the full logs, but most likely you are missing some prerequisites for building wxPython.  See here: https://github.com/wxWidgets/Phoenix#prerequisites

**Comment by rokejulianlockhart** [comment]
@swt2c, what logs do you need?

**Comment by swt2c** [comment]
I am not sure where pip writes logs by default (or if it does?) but you can try to add the `--log LOG_FILE` to your pip command to have it log to a file.  For example `pip install wxpython --log /tmp/wxpython_install.log`.

**Comment by kevinlindstrom** [comment]
I had this issue, so I pip installed attrdict and wheel and that provided me a different error in the install which is shown in [this thread](https://github.com/wxWidgets/Phoenix/issues/2400). The subsequent error with the collections package appears to be an issue introduced after python3.9. 

I simply reverted to version 3.9 and was able to install with no issues.

Good luck, hope this helps.

**Comment by rokejulianlockhart** [comment]
@swt2c,

```log
PS /home/rokejulianlockhart> python3 -m pip install wxPython --log $HOME/wxpython_install.log
Defaulting to user installation because normal site-packages is not writeable
Collecting wxPython
  Downloading wxPython-4.2.1.tar.gz (73.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.7/73.7 MB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pillow in ./.local/lib/python3.10/site-packages (from wxPython) (9.4.0)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from wxPython) (1.16.0)
Requirement already satisfied: numpy in /usr/lib64/python3.10/site-packages (from wxPython) (1.24.2)
Building wheels for collected packages: wxPython
  error: subprocess-exited-with-error
  
  × Building wheel for wxPython (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for wxPython (pyproject.toml) ... error
  ERROR: Failed building wheel for wxPython
Failed to build wxPython
ERROR: Could not build wheels for wxPython, which is required to install pyproject.toml-based projects
PS /home/rokejulianlockhart>
```

[wxpython_install.log](https://github.com/wxWidgets/Phoenix/files/11710330/wxpython_install.log)

**Comment by swt2c** [comment]
@rokejulianlockhart, from your log, this is the relevant part:
```
2023-06-09T22:49:50,523   checking for GTK+ - version >= 3.0.0... no
2023-06-09T22:49:50,523   *** Could not run GTK+ test program, checking why...
2023-06-09T22:49:50,533   *** The test program failed to compile or link. See the file config.log for the
2023-06-09T22:49:50,533   *** exact error that occurred. This usually means GTK+ is incorrectly installed.
2023-06-09T22:49:50,534   configure: error:
2023-06-09T22:49:50,534   The development files for GTK+ were not found. For GTK+ 2, please
2023-06-09T22:49:50,535   ensure that pkg-config is in the path and that gtk+-2.0.pc is
2023-06-09T22:49:50,535   installed. For GTK+ 1.2 please check that gtk-config is in the path,
2023-06-09T22:49:50,535   and that the version is 1.2.3 or above. Also check that the
2023-06-09T22:49:50,535   libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
2023-06-09T22:49:50,535   --libs' are in the LD_LIBRARY_PATH or equivalent.
```
You're missing prerequisites: the GTK+3 development packages.  It appears you're using OpenSUSE?  So, the package might be `gtk3-devel`?

See here for more documentation about prerequisites:
https://github.com/wxWidgets/Phoenix#prerequisites

**Comment by rokejulianlockhart** [comment]
@swt2c, does the ReadMe state that that should be installed? If I've just missed instructions, then I'll close the issue.
