### ISSUE TITLE
Errors when using wx.lib.wxcairo.ContextFromDC

### ISSUE THREAD

**Issue by manns** [wxWidgets/Phoenix#241]
I am trying to create a Cairo context from a wx.MemoryDC in Phoenix using GTK3.
I am using Python 3.5.3 on Debian sid, wxPython checkout 929a8afcc7344fe4c7f80247c1839a593f61f8de
with Subproject commit dc7acca2cd4c87fb2541df17d8b4d80e0f607cc8

```python
import wx
import wx.lib.wxcairo


class Frame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None)
        mdc = wx.MemoryDC()
        bmp = wx.Bitmap(10, 10)
        mdc.SelectObject(bmp)

        context = wx.lib.wxcairo.ContextFromDC(mdc)


app = wx.App(redirect=False)
top = Frame()

top.Show()
app.MainLoop()
```

However, I get the following error message:
```
$ python3 test_cairo.py 
Gtk-Message: (for origin information, set GTK_DEBUG): failed to
retrieve property `gtk-primary-button-warps-slider' of type `gboolean'
from rc file value "((GString*) 0x55b6d256b180)" of type `gboolean'
Traceback (most recent call last): File "test_cairo.py", line 14, in
<module> top = Frame() File "test_cairo.py", line 11, in __init__
    context = wx.lib.wxcairo.ContextFromDC(mdc)
  File "/home/mn/prog/Phoenix/wx/lib/wxcairo/__init__.py", line 80, in
ContextFromDC return _ContextFromDC(dc)
  File "/home/mn/prog/Phoenix/wx/lib/wxcairo/wx_cairocffi.py", line
104, in _ContextFromDC ctx = cairocffi.Context._from_pointer(ctxptr,
False) File "/usr/lib/python3/dist-packages/cairocffi/context.py", line
126, in _from_pointer cls._init_pointer(self, pointer)
  File "/usr/lib/python3/dist-packages/cairocffi/context.py", line 104,
in _init_pointer self._pointer = ffi.gc(pointer, cairo.cairo_destroy)
TypeError: gc() argument 1 must be _cffi_backend.CData, not int
/home/mn/prog/Phoenix/ext/wxWidgets/src/gtk/dcclient.cpp(250): assert
"Assert failure" failed in wxFreePoolGC(): Wrong
GC /home/mn/prog/Phoenix/ext/wxWidgets/src/gtk/dcclient.cpp(250):
assert "Assert failure" failed in wxFreePoolGC(): Wrong
GC /home/mn/prog/Phoenix/ext/wxWidgets/src/gtk/dcclient.cpp(250):
assert "Assert failure" failed in wxFreePoolGC(): Wrong
GC /home/mn/prog/Phoenix/ext/wxWidgets/src/gtk/dcclient.cpp(250):
assert "Assert failure" failed in wxFreePoolGC(): Wrong GC
```

I expected that line 11 would provide a cairo context.

**Comment by RobinD42** [comment]
Do you have the cairocffi package installed, or pycairo?

**Comment by manns** [comment]
On Monday, February 27, 2017 2:23:27 PM CET Robin Dunn wrote:
>Do you have the cairocffi package installed, or pycairo?

Yes, I have installed cairocffi.

```
python3-cairocffi/unstable,unstable,testing,testing,now 0.7.2-1 all 
[installed]
  cffi-based cairo bindings for Python (Python3)
```

**Comment by manns** [comment]
I have now installed the dev packages of anything that sounded like cairo, pycairo, cffi, etc. Afterwards, I have pulled Phoenix again and re-built everything.

Unfortunately, the behavior stays the same.

Are there specific files that Phoenix expects in certain locations for cairo contexts to work?

**Comment by RobinD42** [comment]
I should have looked closer at the traceback you reported, I wasn't seeing the problem because I was working with a gtk3 build instead of the default gtk2, and it was a gtk2-specific code path with the problem.  It's a simple little 1-line fix that will be in the next snapshot build.
