### ISSUE TITLE
v4.2.1 build failure on Linux and macOS for Homebrew

### ISSUE THREAD

**Issue by p-linnane** [wxWidgets/Phoenix#2414]
**Operating system**: Ubuntu 22.04.2, macOS 11, macOS 12, macOS 13
**wxPython version & source**:          Building from PyPI source distribution
**Python version & source**:            Python 3.11 from Homebrew

**Description of the problem**:

Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v4.2.1 of wxpython we are encountering a build failure while running the `etg` command. Any help would be appreciated.

<details>
  <summary>Code Example (click to expand)</summary>

```python
python3.11 -u build.py dox touch etg sip build_py --release --use_syswx --prefix=/home/linuxbrew/.linuxbrew/Cellar/wxpython/4.2.1 --jobs=2 --verbose --nodoc
  Will build using: "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11"
  3.11.3 (main, Apr  4 2023, 22:36:41) [GCC 11.3.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.2.1
  
  Running command: dox
  bash ./regen.sh xml
  warning: Tag 'HTML_TIMESTAMP' at line 364 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'FORMULA_TRANSPARENT' at line 426 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'LATEX_SOURCE_CODE' at line 459 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 501 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'CLASS_DIAGRAMS' at line 552 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'DOT_FONTNAME' at line 557 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'DOT_FONTSIZE' at line 558 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  warning: Tag 'DOT_TRANSPARENT' at line 581 of file 'Doxyfile' has become obsolete.
           To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  Finished command: dox (0m9.389s)
  Running command: touch
  Running command: touch_others
  Finished command: touch_others (0.0s)
  Finished command: touch (0.2s)
  Running command: etg
  "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_core.py --sip --nodoc
  "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_ribbon.py --sip --nodoc
  "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_grid.py --sip --nodoc
  "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_xrc.py --sip --nodoc
  "/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_glcanvas.py --sip --nodoc
  Traceback (most recent call last):
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etg/_glcanvas.py", line 137, in <module>
      run()
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etg/_glcanvas.py", line 49, in run
      etgtools.parseDoxyXML(module, ITEMS)
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/__init__.py", line 91, in parseDoxyXML
      item = module.addElement(element)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/extractors.py", line 1576, in addElement
      self.addElement(node)
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/extractors.py", line 1547, in addElement
      item = EnumDef(element, inClass)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/extractors.py", line 1185, in __init__
      self.extract(element)
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/extractors.py", line 1189, in extract
      super(EnumDef, self).extract(element)
    File "/tmp/wxpython-20230608-41304-1ryj0qe/wxPython-4.2.1/etgtools/extractors.py", line 65, in extract
      if '::' in self.name:
         ^^^^^^^^^^^^^^^^^
  TypeError: argument of type 'NoneType' is not iterable
  Command '"/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11" etg/_glcanvas.py --sip --nodoc' failed with exit code 1.
  Finished command: etg (0m1.597s)
```
</details>

Relates to https://github.com/Homebrew/homebrew-core/pull/133134

**Comment by swt2c** [comment]
I'm assuming you're using Doxygen 1.9.7?  Unfortunately, they changed a bunch of stuff in that version that broke wxPython's build.  I haven't sorted out all of the fixes yet, unfortunately.  As a workaround, you can use Doxygen 1.9.6 or older.

**Comment by p-linnane** [comment]
Yes, we always build against the latest version of dependencies in Homebrew. I will make a note to check back in to see when Doxygen 1.9.7 is supported.

**Comment by RobinD42** [comment]
Another option would be to use the source tarball, as it includes the results of the code generation steps (the dox, etg and sip subcommands.)

**Comment by StefanBruens** [comment]
Actually, I can't see see a reason why this should be considered fixed.

The doxygen 1.9.7 output changed as a bug got fixed there, and doxygen no longer issues incorrect XML.

The anonymous enum in https://github.com/wxWidgets/wxWidgets/blob/eb8a57760e61e72959593200d4df8d8b36dfb87a/interface/wx/glcanvas.h#L553 had an incorrect (random!) `<name>` tag  up to doxygen 1.9.6, now it correctly! is empty.

When the empty tag (which becomes `None` in  Python) is parsed here https://github.com/wxWidgets/Phoenix/blob/a1184286703cf24c4b88e5bc14cf2979c1b1ea00/etgtools/extractors.py#L65, Python complains it can't iterate a `NoneType` (it expects a string).

**Comment by StefanBruens** [comment]
Upstream issue (closed "intentional"), and original change:
https://github.com/doxygen/doxygen/issues/10071
https://github.com/doxygen/doxygen/pull/9976

**Comment by swt2c** [comment]
I'm aware - I filed that issue.  :P  There are unfortunately more Doxygen 1.9.7 changes that broke the wxPython build than that one.

**Comment by p-linnane** [comment]
I opened this issue specific to Homebrew. Our issue has been resolved, so I am going to close this again and request someone open a different, general Doxygen issue if this is ongoing.
