### ISSUE TITLE
_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN13wxWindowIDRef6AssignEi, version WXU_3.2

### ISSUE THREAD

**Issue by Szirenke** [wxWidgets/Phoenix#2444]
Hi,

I am having some issues running wxpython on Ubuntu 22.04. I have now read most of the related issues and none of them helped. I have now installed wxpython in many ways including conda environment with python 3.7. This was the only installation which sort of worked. I write sort of because matplotlib gives an error of singular matrices when I involve axes.axhline. I thought I try a different version and I followed the recipe here at Phoenix and compiled wxpython from source. I could never import wx due to undefined symbol error. (_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN13wxWindowIDRef6AssignEi, version WXU_3.2) The weird thing is that using the conda environment on a windows 11 machine with python 3.7 actually works and no matplotlib error is thrown. This is the first time in my life that something worked under windows and didnt under linux. What could cause the above error? I tried to install wxpython with pip but that gives the same error. I tried many of the suggestion around but nothing helped apart from using conda with python 3.7 but that one has a matplotlib bug it seems. The compilation from source finishes without any issues (python3.10) and yet after putting all the proper folders to pythonpath and ld_library_path I get the undefined symbol error. Is there a solution to this?

Thanks

**Comment by swt2c** [comment]
It's unclear why you are getting that error, but we'd need to know a lot more about what you did/how you attempted to compile wxPython.

In any event, if you don't *really* want to compile wxPython, but just want to install it, probably the easiest way is to use one of the wheels here: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/

**Comment by Szirenke** [comment]
Hi, 

Thanks for the answer! I will try the wheel you shared on my virtual box ubuntu since I moved my "operation" to windows for the moment due to the lack of quick fix. At least on windows I have a working matplotlib as well under conda python 3.7. I will resume with results of the above wheel shortly. 

Thanks again

**Comment by rcardenes** [comment]
I'm having the same problem on a Debian unstable. The Python I'm using though is a 3.12.2 installed using pyenv. In installed wxPython using pip

**Comment by SunJun8** [comment]
I am using Ubuntu 24.04 and installed Python 3.9.1 via pyenv, and I encountered a similar issue:  
`_core.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK12wxDataFormateqERKS_, version WXU_3.2`

**Comment by jmoraleda** [comment]
Have you tried compiling from a worktree you just cloned or a worktree just created from `git worktree add ...` because it is known that the wxPython builds are "in-source" and some times no amount of cleaning an old worktree from which you compiled an old version will produce a _clean enough_ source tree, including `python build.py cleanall` and `git clean -fx`.

The undefined symbol errors at runtime reported in this issue are an example of what can happen when compiling from an updated worktree as opposed to a brand new one. It just bit me today. After cleaning and  _successfully compiling_, when I tried to run I got:
```
  File "/home/jorge/vc/meticy-client/src/meticy/_starter.py", line 21, in <module>
    import wx
  File "/usr/local/lib/python3.11/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.11/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /usr/local/lib/python3.11/dist-packages/wx/_core.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN14wxTranslations19AddAvailableCatalogERK8wxString10wxLanguage, version WXU_3.2
```

But after compiling and reinstalling from a brand new tree (instead from my old one that I had just updated and cleaned) the error went away.

**Comment by Vo10dymyr** [comment]
> I am using Ubuntu 24.04 and installed Python 3.9.1 via pyenv, and I encountered a similar issue: `_core.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK12wxDataFormateqERKS_, version WXU_3.2`

This will help, at least it helped me
```
rm -rf ~/.pyenv
sed -i '/pyenv/d' ~/.bashrc ~/.bash_profile ~/.zshrc 2>/dev/null
exec $SHELL
```
this remove your pyenv

**Comment by h4ppyr0gu3** [comment]
I have the same issue on arch linux, not sure how to describe steps to reproduce, I am using python 3.12.10

**Comment by echoix** [comment]
The project here is rather https://pypi.org/project/wxPython/

**Comment by LucasMembrane** [comment]
I have been to 

 https://pypi.org/project/wxPython/

It says for windows and macOS:   pip install -U wxPython  

When I run that on fedora, I  revisit the same error by which I am otherwise confounded. Neither does pip uninstalling wxWidgets cut any notches on the waterpistol.  I guessed that I had to have wxWidgets to provide the C and C++ implementation that wxPython would call.

I was not able to use pypi to search for solutions to this problem this week, because the request for funds filled my entire screen and couldn't be gotten around whenever I used google Chrome to access their site.  Just now, I used Firefox and it allowed me to see  https://pypi.org/project/wxPython/.   

Is there any short and sweet way to install  the https://pypi.org/project/wxPython/
project on fedora 42?  I saw the link to Index of /wxPython4/extras/linux/gtk3, but it does not have any wheels newer than fedora 38.   I have installed 
python3-wxpython4 from fedora using dnf, and set my pyenv to reference the system installed packages, but I cannot find any relevant  python wx packages after doing that.  

Baffled and Flummoxed am I.  Thanks much for trying and TIA to anyone who can get me going.

**Comment by swt2c** [comment]
If you just want a working build of wxPython on Fedora, you can just do `dnf install python3-wxpython4`.

**Comment by LucasMembrane** [comment]
> install python3-wxpython4

I just did that:

(fedora) $ /usr/lib64/python3.13
18 > sudo dnf install python3-wxpython4
Updating and loading repositories:
Repositories loaded.
Package                           Arch      Version                           Repository             Size
Installing:
 python3-wxpython4                x86_64    4.2.2-2.fc42                      fedora             48.5 MiB

Transaction Summary:
 Installing:         1 package

Total size of inbound packages is 10 MiB. Need to download 10 MiB.
After this operation, 49 MiB extra will be used (install 49 MiB, remove 0 B).
Is this ok [y/N]: Y
[1/1] python3-wxpython4-0:4.2.2-2.fc42.x86_64                    100% |   6.7 MiB/s |   9.6 MiB |  00m01s
---------------------------------------------------------------------------------------------------------
[1/1] Total                                                      100% |   5.4 MiB/s |   9.6 MiB |  00m02s
Running transaction
[1/3] Verify package files                                       100% |  40.0   B/s |   1.0   B |  00m00s
[2/3] Prepare transaction                                        100% |   1.0   B/s |   1.0   B |  00m01s
[3/3] Installing python3-wxpython4-0:4.2.2-2.fc42.x86_64         100% |   3.5 MiB/s |  48.7 MiB |  00m14s
Complete!

Then

(fedora) $ /usr/lib64/python3.13
21 > python
Python 3.13.9 (main, Oct 14 2025, 00:00:00) [GCC 15.2.1 20250808 (Red Hat 15.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import wx
  File "/home/xxx/.local/lib/python3.13/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/xxx/.local/lib/python3.13/site-packages/wx/core.py", line 12, in module>
    from ._core import *
ImportError: /home/xxx/.local/lib/python3.13/site-packages/wx/_core.cpython-313-x86_64-linux-gnu.so: undefined symbol: _ZN13wxWindowIDRef6AssignEi, version WXU_3.2
>>> 

Is that supposed to work?  There tain't any of my code running in the above.
But two things are wrong.  First, the python3-wxpython4-0:4.2.2-2.fc42.x86_64 package got installed into the (fedora) pyenv virtual environment,  which is /usr/lib64/python3.13/site-packages.  The directory in the error message for the python modules in site-packages is 
/home/xxx/.local/lib/python3.13/site-packages/wx/.   The paths that I see when I run python are:

(fedora) $ /usr/lib64/python3.13
> python
Python 3.13.9 (main, Oct 14 2025, 00:00:00) [GCC 15.2.1 20250808 (Red Hat 15.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import sys
>>> sys.path
['', '/usr/lib64/python313.zip', '/usr/lib64/python3.13', '/usr/lib64/python3.13/lib-dynload',  ... etc
 
There is a wx  library installed in /usr/lib64/python3.13/site-packages  and it
appeared there when I ran the install shown above.  It looks like it got passed over for some reason when the import was done from /home/xxx/.local/lib/python3.13/site-packages/wx    instead. What would cause that?      
 
/home/xxx/.local/lib/python3.13/site-packages/wx is in the list of folders that show up on the path for pyenv.  It is a not a virtual environment, just a pyenv option that uses python 3.13.5.    And the second thing that looks wrong is that the version of wx that I get when I run 'sudo dnf install python3-wxpython4' with pyenv set to 3.13.5 is not 4.2.2, as above, but 4.2.4.   So I have the higher version of python compiler matched to the  lower version of wx and vice versa.   Neither of these configurations works (each dies with a message with that wxWindoID message .  I  suppose that things are the way they are because they got that way, and there must be version and/or package differences between the respective site-packages folders that have made meatballs out of my spaghetti or vice versa.  But the version number differences are so small and the messages so similar that it is hard to infer that these observed differences cause the error. Perhaps you know(???).

My fedora 42 install is about 5 months old.  I've run 'sudo dnf update'  just about every day and I use fedora 42 because it appears to get the security updates to the front as fast as any good developers' release,  and I've tried to avoid installing anything except through dnf.  My experience with linux for almost 20 years, however, is to expect that it is very hard to keep the entire herd singing off the same sheet for much more than a year, it being so unlikely that so many packages  can live together that long without a few bustages.  Is this just one of those cases?

**Comment by CiderMan** [comment]
In case this is useful, I encountered this problem and, after a bit of investigation, have figured out the problem (for my use-case, at least) and I've been able to work around it.

# The use-case

Everyone uses a standard OS configuration but we use a version of Python built from source, rather than the system Python, so we want to build a wheel for wxPython (and a bunch of other packages), which can then be used by everyone. We do this using the `pip wheel` command.

# The issue

This does produce a wheel for wxPython, which contains all the expected `.so` files when installed into a venv. However, when we use it, we get the `ImportError` that is being reported here.

# The workaround

The issue seems to be that the RPATH hasn't been set in the `.so` files. Hence, I have updated the venv creation script (which installs the wheels that have been built) to patch the RPATH for all the `.so` in the `wx` directory: `patchelf --set-rpath '$ORIGIN' "$so_file"`

With this workaround, I can finally import wxPython successfully within the venv.

I hope that this is helpful for others but I would also be interested to know whether I can change the `pip wheel` command to produce a wheel that does not need patching!

**Comment by swt2c** [comment]
I believe all these issues stem back to setting the RPATH (or lack thereof) and have been resolved in v4.3.1.
