### ISSUE TITLE
wxdemo/GLCanvas [Cube] window is broken

### ISSUE THREAD

**Issue by komoto48g** [wxWidgets/Phoenix#2481]
**Operating system**: Windows 10
**wxPython version & source**: 4.2.1 (pypi)
**Python version & source**: 3.11

**Description of the problem**: wxdemo/GLCanvas [Cube] window is broken.

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Run wxdemo, select Misc/GLCanvas, and press [Cube] button
```
</details>

```bash
Traceback (most recent call last):
  File "GLCanvas.py", line 116, in OnPaint
    self.InitGL()
  File "GLCanvas.py", line 204, in InitGL
    self.textureID = GenerateTexture(*ReadTexture(os.path.join(path, rd)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "GLCanvas.py", line 157, in GenerateTexture
    glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)
  File "c:\Python311\Lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'\x96\xb3\x8c\xf8\x82\xc8\x97\xf1\x8b\x93',
        baseOperation = glTexParameterf,
        cArguments = (
                GL_TEXTURE_2D,
                GL_TEXTURE_WRAP_S,
                GL_CLAMP_TO_EDGE,
        )
)
```

**Comment by Metallicow** [comment]
@komoto48g ... 
What Demo version are you using...?

SourceCoder is running at all too this and this without no problems...

```python
wxPython 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5 Scintilla 3.21
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32

wxPython 4.2.2a1.dev5626+a1184286 msw (phoenix) wxWidgets 3.2.3 Scintilla 3.7.2
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
```

**Comment by komoto48g** [comment]
I'm using:
```python
wxPython 4.2.1 msw (phoenix) wxWidgets 3.2.2.1
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
```
I also tested:
```python
wxPython 4.2.2a1.dev5626+a1184286 msw (phoenix) wxWidgets 3.2.3
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
```
with the corresponding demo version, but the same problem occurred. The error when calling glTexParameterf is `GL_INVALID_ENUM (0x500)`.

**Comment by Metallicow** [comment]
@komoto48g Ummmmm Yeah... It's one of those weird things... Ask them and get back ok... Might be a minuite or two...

```python
C:\Users\Admin\Downloads\wxPython-demo-4.2.2a1.dev5626+a1184286\demo>pip3 install OpenGL_accelerate
ERROR: Could not find a version that satisfies the requirement OpenGL_accelerate (from versions: none)
```

... it is always ready to tell me if  '```pip```' is outdated...

... A bunch of garbage advertising bullshit in my opinion. But PYPI needs funds so add ADs withouth spam so to speak.

**Comment by Metallicow** [comment]
If I could click a button and donate $5bucks, I would but github doesn't allow that behaviouvr

**Comment by komoto48g** [comment]
The official version of PyPI for Windows doesn't seem to work (I think it's because of missing DLLs) 🙄.
So I installed the unofficial version 3.1.6 for cp311 found here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl.
It works fine, but wxdemo cube doesn't work... The current version of freeglut.dll is 3.0.0 (from 'freeglut_README.txt').
```python
>>> from OpenGL.GLUT import GLUT
>>> GLUT
<WinDLL 'C:\Python311\Lib\site-packages\OpenGL\DLLS\freeglut64.vc16.dll', handle 7ffcd1f20000 at 0x1dc19d6ced0>
```
