### ISSUE TITLE
Strange Failure after update

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#249]
```

  _____                                _____           _
 / ____|                              / ____|         | |
| (___   ___  _   _  _ __  ___   ___ | |      ___   __| | ___  _ __
 \___ \ / _ \| | | || '__|/ __| / _ \| |     / _ \ / _` |/ _ \| '__|
 ____) | (_) | |_| || |  | (__ |  __/| |____| (_) | (_| |  __/| |
|_____/ \___/ \__,_||_|   \___| \___| \_____|\___/ \__,_|\___||_|

sys.version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32
 bit (Intel)]
wx.VERSION = (3, 0, 3, '.dev2864+4fc5f9e')
FAILED importing wx.gizmos
Running Python 2
Traceback (most recent call last):
  File "C:\Users\redteam316\Desktop\SourceCoder_Source\SourceCoder.py", line 291
, in <module>
    from src.STCModule import SrcCoderSTC, PlainSTC, DummySTC, HijackExtendAutoC
ompBox
  File "C:\Users\redteam316\Desktop\SourceCoder_Source\src\STCModule.py", line 1
08, in <module>
    raise exc  # Bare Exception!
wx._core.PyNoAppError: The wx.App object must be created first!

C:\Users\redteam316\Desktop\SourceCoder_Source>
```

**Comment by Metallicow** [comment]
its got something todo with..

```
try:
    STC_LIBRARY_VERSION_INFO = wx.stc.StyledTextCtrl.GetLibraryVersionInfo()  # staticmethod
    if STC_LIBRARY_VERSION_INFO.HasCopyright():
        SCINTILLA_COPYRIGHT = STC_LIBRARY_VERSION_INFO.GetDescription()
    if STC_LIBRARY_VERSION_INFO.HasDescription():
        SCINTILLA_DESCRIPTION = STC_LIBRARY_VERSION_INFO.GetDescription()
    SCINTILLA_VERSION = ('%i.%i.%i' %
        (STC_LIBRARY_VERSION_INFO.GetMajor(),
         STC_LIBRARY_VERSION_INFO.GetMinor(),
         STC_LIBRARY_VERSION_INFO.GetMicro()))
    SCINTILLA_NAME = STC_LIBRARY_VERSION_INFO.GetName()
    SCINTILLA_VERSION_STRING = STC_LIBRARY_VERSION_INFO.GetVersionString()
except Exception as exc:
    raise exc  # Bare Exception!
```
stuff....

**Comment by Metallicow** [comment]
updated after "lots of propgrid fixes"

**Comment by RobinD42** [comment]
It was due to changes in PR #211. I'm not sure now why I also propagated the setting to static methods (see bd0927fb02aeaa6ee6923d0b841d86c148d6ef86) but I'll try to recall that and see if there is a better way to deal with it.
