### ISSUE TITLE
"python build.py dox && python build.py build_wx --jobs=4 && python build.py etg --nodoc && python build.py sip && python build.py build_py --jobs=4" fails due to "etgtools.extractors.ExtractorError: Unable to find item named 'SetPolarCoordinates' within ClassDef named 'wxPoint2DDouble'"

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#264]
The failing part is

```
Running command: etg
"/usr/bin/python" etg/_core.py --sip --nodoc
"/usr/bin/python" etg/_stc.py --sip --nodoc
"/usr/bin/python" etg/_webkit.py --sip --nodoc
"/usr/bin/python" etg/_glcanvas.py --sip --nodoc
"/usr/bin/python" etg/_aui.py --sip --nodoc
"/usr/bin/python" etg/_adv.py --sip --nodoc
"/usr/bin/python" etg/_richtext.py --sip --nodoc
"/usr/bin/python" etg/_ribbon.py --sip --nodoc
"/usr/bin/python" etg/_propgrid.py --sip --nodoc
"/usr/bin/python" etg/_dataview.py --sip --nodoc
"/usr/bin/python" etg/_html.py --sip --nodoc
"/usr/bin/python" etg/_msw.py --sip --nodoc
"/usr/bin/python" etg/_xml.py --sip --nodoc
"/usr/bin/python" etg/_html2.py --sip --nodoc
"/usr/bin/python" etg/_media.py --sip --nodoc
"/usr/bin/python" etg/_xrc.py --sip --nodoc
"/usr/bin/python" etg/_grid.py --sip --nodoc
"/usr/bin/python" etg/defs.py --sip --nodoc
"/usr/bin/python" etg/debug.py --sip --nodoc
"/usr/bin/python" etg/object.py --sip --nodoc
"/usr/bin/python" etg/clntdatactnr.py --sip --nodoc
"/usr/bin/python" etg/wxdatetime.py --sip --nodoc
"/usr/bin/python" etg/stopwatch.py --sip --nodoc
"/usr/bin/python" etg/windowid.py --sip --nodoc
"/usr/bin/python" etg/platinfo.py --sip --nodoc
"/usr/bin/python" etg/vidmode.py --sip --nodoc
"/usr/bin/python" etg/display.py --sip --nodoc
"/usr/bin/python" etg/intl.py --sip --nodoc
"/usr/bin/python" etg/translation.py --sip --nodoc
"/usr/bin/python" etg/cmndata.py --sip --nodoc
"/usr/bin/python" etg/gdicmn.py --sip --nodoc
"/usr/bin/python" etg/geometry.py --sip --nodoc
Traceback (most recent call last):
  File "etg/geometry.py", line 139, in <module>
    run()
  File "etg/geometry.py", line 54, in run
    c.find('SetPolarCoordinates').ignore()
  File "/mnt/data/sources/Phoenix/etgtools/extractors.py", line 99, in find
    (head, self.__class__.__name__, self.name))
etgtools.extractors.ExtractorError: Unable to find item named 'SetPolarCoordinates' within ClassDef named 'wxPoint2DDouble'
Command '"/usr/bin/python" etg/geometry.py --sip --nodoc' failed with exit code 1.
Finished command: etg (8.356s)
```

find the complete build log at https://richtercloud.de:451/index.php/s/rnqQBGdyBEqBxmE

experienced with 9b743cf3

**Comment by swt2c** [comment]
From your log:

> Configured wxWidgets 3.1.1 for `x86_64-unknown-linux-gnu'

Somehow you built wxWidgets 3.1.1.

**Comment by krichter722** [comment]
> From your log:
>
>>   Configured wxWidgets 3.1.1 for `x86_64-unknown-linux-gnu'
>
>Somehow you built wxWidgets 3.1.1.

Right, I needed to get the required `ext/wxWidets` commit with `git diff` and then `git reset --hard [commit]` in the submodule. Thank you!
