### ISSUE TITLE
Errors when using wx.lib.plot.PlotCanvas.Draw

### ISSUE THREAD

**Issue by wossx** [wxWidgets/Phoenix#283]
Since Build 2902 my script give this error message:
     .......
     self.canvas.Draw(self.Graphics())
  File "d:\python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1743, in Draw
    self._Draw(graphics, xAxis, yAxis, dc)
  File "d:\python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1914, in _Draw
    graphics.draw(dc)
  File "d:\python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 1421, in draw
    o.draw(dc, self._printerScale)
  File "d:\python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 426, in draw
    self._path(dc, c1, c2, drawstyle)
  File "d:\python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 481, in _path
    dc.DrawLines(line)
TypeError: DC.DrawLines(): argument 1 has unexpected type 'list'

The runnable example    wx/lib/plot/examples/simple_example.py    give this:

Traceback (most recent call last):
  File "simple_example.py", line 56, in <module>
    frame = PlotExample()
  File "simple_example.py", line 51, in __init__
    panel.Draw(graphics)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1743, in Draw
    self._Draw(graphics, xAxis, yAxis, dc)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1914, in _Draw
    graphics.draw(dc)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 1421, in draw
    o.draw(dc, self._printerScale)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 526, in draw
    dc.DrawSpline(self.scaled)
TypeError: DC.DrawSpline(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'numpy.ndarray'
  overload 2: argument 1 has unexpected type 'numpy.ndarray'

With Build 2891 works fine.

OS: Win 7
Py: 2.7 and/or 3.6

**Comment by RobinD42** [comment]
Is that the only place that needs to be changed?

**Comment by belangeo** [comment]
I'm working on a big project using phoenix for the interface ( https://github.com/belangeo/cecilia5 ) and I didn't have to change anything else...

**Comment by wossx** [comment]
Of course is not enough.

For example:  wx/lib/plot/examples/demo.py
The 1st item in Plot menü : "Plot / Draw-1: sin, cos" 

Traceback (most recent call last):
  File "demo.py", line 638, in OnPlotDraw1
    self.client.Draw(_draw1Objects())
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1743, in Draw
    self._Draw(graphics, xAxis, yAxis, dc)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\plotcanvas.py", line 1914, in _Draw
    graphics.draw(dc)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 1421, in draw
    o.draw(dc, self._printerScale)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 426, in draw
    self._path(dc, c1, c2, drawstyle)
  File "D:\Python27\lib\site-packages\wx-4.0-msw\wx\lib\plot\polyobjects.py", line 481, in _path
    dc.DrawLines(line)
TypeError: DC.DrawLines(): argument 1 has unexpected type 'list'

@belangeo solution is a part solution.

**Comment by belangeo** [comment]
Of course, every method expecting an array of wx.Point(s) don't accept numpy array anymore, that mean almost every DC.DrawXXX methods! I took "only place" as "wx.lib.plot.PlotCanvas", not just the DrawSpline() line, sorry for the confusion!

**Comment by RobinD42** [comment]
Okay, thanks. I figured there would be more needing to be done there.

I'll give it some thought and see if I can get numpy array support in those mapped types again without sacrificing the type safety that the last change gave us.

**Comment by RobinD42** [comment]
Should be fixed in efa81882e33e097998094dc7b889c42f378d0ec7.

**Comment by wossx** [comment]
That works for me.
Thanks Robin.
