### ISSUE TITLE
Masked controls modules and demos need Py3-related fixes

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#303]

**Comment by esitarski** [comment]
How is this going?
The masked control demo seem to work on Windows, but it is easy to mess up the formats and to get errors on Ubuntu.  Just enter valid characters, then go back and type in invalid chars.

----
  File "/home/esitarski/.local/lib/python3.5/site-packages/wx/lib/masked/maskededit.py", line 2703, in _configure
    self._calcTemplate(reset_fillchar, reset_default)
  File "/home/esitarski/.local/lib/python3.5/site-packages/wx/lib/masked/maskededit.py", line 2506, in _calcTemplate
    if curvalue[pos] == old_fillchars[pos] and old_fillchars[pos] != fillChar:
IndexError: list index out of range
esitarski@esitarski-XPS-13-9370:~/Projects/wxPython-demo-4.0.7/demo$ p3 MaskedEditControls.py
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]
wx.version: 4.0.4 gtk3 (phoenix) wxWidgets 3.0.5
Traceback (most recent call last):
  File "/home/esitarski/.local/lib/python3.5/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/esitarski/.local/lib/python3.5/site-packages/wx/lib/masked/maskededit.py", line 5649, in _fixSelection
    elif sel_start > self._goEnd(getPosOnly=True):
  File "/home/esitarski/.local/lib/python3.5/site-packages/wx/lib/masked/maskededit.py", line 4589, in _goEnd
    char = text[i]
IndexError: string index out of range


![image](https://user-images.githubusercontent.com/158633/68062563-858d9380-fce1-11e9-8b5d-7a2897b386ee.png)

**Comment by RobinD42** [comment]
If you're able to fix some of the issues you run into then PRs are welcome. I don't use the masked controls myself so they do not get much of my attention.
