### ISSUE TITLE
PropertyGrid stuff and a crash

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#394]
There is no [Classic vs Phoenix](https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html) entries for the property grid stuff that has been changed.
https://github.com/wxWidgets/Phoenix/commit/38029c973c72075338017c8d4d1f43e6d45865b7

LABEL_AS_NAME to PG_LABEL

...also...

In the demo, wxpg.PGProperty.AddPrivateChild seems to be a **HARD CRASH** culprit for... 
```python
class SizeProperty(wxpg.PGProperty):
    """ Demonstrates a property with few children.
    """
    def __init__(self, label, name = wxpg.PG_LABEL, value=wx.Size(0, 0)):
        wxpg.PGProperty.__init__(self, label, name)

        value = self._ConvertValue(value)

        self.AddPrivateChild( wxpg.IntProperty("X", value=value.x) )
        self.AddPrivateChild( wxpg.IntProperty("Y", value=value.y) )

        self.m_value = value
```
...it works for Classic, what happened?

**Comment by Metallicow** [comment]
@RobinD42 Also `SetAttribute('Password', 1)` for StringProperty is a **HARD CRASH**. `Pazzzzword` works fine.

```python
    def CreatePage_Testing(self):
        pgp = self.AddPage('Page 1 - Testing All Properties', bmp=wx.NullBitmap, pageObj=None)

        pgp.SetColumnProportion(0, 2)
        pgp.SetColumnProportion(1, 1)

        pgp.Append(wxpg.PropertyCategory('1 - Basic Properties'))

        sp = wxpg.StringProperty('StringProperty', value='string')
        sp.SetAttribute('Hint', 'Hint')
        # sp.SetAttribute('Password', 1)  # TODO CRASH this needs fixed in wx
```

**Comment by Metallicow** [comment]
@RobinD42 The SizeProperty you added in the demo in https://github.com/wxWidgets/Phoenix/commit/888e0ef266e9613a9883a98783b9a7fec624a9aa is borked. No matter what you try to edit, the numbers stay the same.

**Comment by RobinD42** [comment]
> @RobinD42 The SizeProperty you added in the demo in 888e0ef is borked. No matter what you try to edit, the numbers stay the same.

It worked here.

**Comment by RobinD42** [comment]
>   `sp.SetAttribute('Password', 1)  # TODO CRASH this needs fixed in wx`

It looks like the property needs to be added to a property grid before that attribute can be changed, because it needs to recreate the editor widget. I'll look and see if there is an easy way to catch that condition and assert or something, but in the meantime, adding this to the demo works for me:

```
        sp = pg.Append( wxpg.StringProperty('StringProperty w/ Password flag', value='ABadPassword') )
        sp.SetAttribute('Hint', 'This is a hint')
        sp.SetAttribute('Password', 1)
```

**Comment by Metallicow** [comment]
OS: Windows7
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
wxPython 4.0.0a4.dev3150+888e0ef msw (phoenix)

1. This error happens on startup.
```
Traceback (most recent call last):
  File "PropertyGrid.py", line 191, in DoSetAttribute
    retval = super(DirsProperty, self).DoSetAttribute(name, value)
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\co
mmon\variant.cpp(837) in wxVariant::GetChar(): Could not convert to a char
```

2. This error happens when scrolling and a DirsProperty is visible.
```
Traceback (most recent call last):
  File "PropertyGrid.py", line 185, in ValueToString
    return self.m_display
AttributeError: 'DirsProperty' object has no attribute 'm_display'
```

3. This error occurs when using the ImageFileWithLargeEditor button.
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\wx-3.0.3-msw-phoenix\wx\propgrid.py", line
 1393, in _PropertyGrid__init__
    self.DoDefaultTypeMappings()
  File "C:\Python27\lib\site-packages\wx-3.0.3-msw-phoenix\wx\propgrid.py", line
 1090, in _PropertyGridInterface_DoDefaultTypeMappings
    import sys
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\co
mmon\valtext.cpp(139) in wxTextValidator::GetTextEntry(): wxTextValidator can on
ly be used with wxTextCtrl, wxComboBox, or wxComboCtrl
```

4. This error occurs when pressing the `Run Tests` button.
```
Traceback (most recent call last):
  File "PropertyGrid.py", line 943, in RunTests
    raise ValueError("Set/GetPropertyClientData() failed")
ValueError: Set/GetPropertyClientData() failed
```

5. SizeProperty still won't change it's initial value. nomatter what.

**Comment by Metallicow** [comment]
@RobinD42 This change makes it work as expected on Windows. Strange it works on classic your way, but not on Phoenix(Windows). What is the `self._ConvertValue` meth needed for anyway? Is it really needed ... or should you look deeper into the problem? Does removing the method call work for you also? And what platform did you test?

```python
    def ChildChanged(self, thisValue, childIndex, childValue):
        ## size = self._ConvertValue(self.m_value)
        size = self.m_value
        if childIndex == 0:
            size.x = childValue
        elif childIndex == 1:
            size.y = childValue
        else:
            raise AssertionError

        return size
```

**Comment by Metallicow** [comment]
OS: Win7
Color Issue
Bug: This changes the cell Background colour to Black. 
```python
        p2 = wxpg.IntProperty('ChangePropertyCellBitmap', value=1)
        p2.GetCell(0).SetBitmap(gImgIdx['python16.png'])
        p2.GetCell(1).SetBitmap(gImgIdx['snakey_green16.png'])
        pgp.Append(p2)
```

This makes it bearable.
```python
        p2 = wxpg.IntProperty('ChangePropertyCellBitmap', value=1)
        p2.GetCell(0).SetBgCol(wx.WHITE)  # HMM Was changing to black/or system colour.
        p2.GetCell(1).SetBgCol(wx.WHITE)  # HMM Was changing to black/or system colour.
        p2.GetCell(0).SetBitmap(gImgIdx['python16.png'])
        p2.GetCell(1).SetBitmap(gImgIdx['snakey_green16.png'])
        pgp.Append(p2)
```

Adding this line makes it **HARD CRASH**.
```python
        p2 = wxpg.IntProperty('ChangePropertyCellBitmap', value=1)
        bgColor = p2.GetCell(0).GetBgCol()  # HARD CRASH
        p2.GetCell(0).SetBgCol(bgColor)  # HMM Was changing to black/or system colour.
        p2.GetCell(1).SetBgCol(bgColor)  # HMM Was changing to black/or system colour.
        p2.GetCell(0).SetBitmap(gImgIdx['python16.png'])
        p2.GetCell(1).SetBitmap(gImgIdx['snakey_green16.png'])
        pgp.Append(p2)
```

This works as expected.
```python
        p2 = wxpg.IntProperty('ChangePropertyCellBitmap', value=1)
        pgp.Append(p2)
        p2.GetCell(0).SetBitmap(gImgIdx['python16.png'])
        p2.GetCell(1).SetBitmap(gImgIdx['snakey_green16.png'])
```

**Comment by Metallicow** [comment]
Missing Window Styles Docs:

https://wxpython.org/Phoenix/docs/html/wx.propgrid.PropertyGridManager.html#phoenix-title-window-styles
and
https://wxpython.org/Phoenix/docs/html/wx.propgrid.PropertyGrid.html#phoenix-title-window-styles

both say this with no link.

`See PropertyGrid Window Styles.`

**Comment by RobinD42** [comment]
> Edit2: Shouldn't the attributes for wx.Size be width, height, and x, y for wx.Point?

They're actually `x` and `y` in the C++ version of the class. IIRC the rationale was something like "it's the size in the `x` dimension," or something silly like that. I added `width` and `height` for the Python wrappers a couple decades ago, however I suspect that at least most of this demo was just ported directly from the C++ sample so that is why things like that are present.

> What is the self._ConvertValue meth needed for anyway? 

Probably another C++-ism. The value is a `wxVariant` in C++ which needs an extra step to convert it to a `wxSize`. That conversion is handled for us in wxPython's mapped type for `wxVariant`, although if it's possible that the value was not a `wx.Size` to begin with (some 2-element sequence for example) then it's probably a good idea to still go through the conversion step for those cases.

**Comment by RobinD42** [comment]
There's probably still a few things that the latest merge hasn't fixed, but the nastiest should now be solved so it seemed like a good time to merge it.  I'll leave this open for now however.
