### ISSUE TITLE
HitTest creates AttributeError: 'float' object has no attribute '_itemId'

### ISSUE THREAD

**Issue by finchyfinch** [wxWidgets/Phoenix#528]
**Operating system**: Win 8 (also confirmed on Win 10
**wxPython version**: 4.0.0b2.dev3337+03248e0 msw (phoenix)
**Stock or custom build**: stock
**Python version**: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
**Stock or custom build**: Stock

**Description of the problem**:  I have Virtual List and use a right click event to find the row selected by using hittest;

pt = event.GetPosition()
item, flags = self.list.HitTest(pt)

In classic wxPython this worked ok.  In Phoenix it generates an exception as follows;
Traceback (most recent call last):
  File "C:/temp/pfemame_source_v1.009/pfemame.py", line 1051, in OnRightDown
    item, flags = self.list.HitTest(pt)
  File "C:\Users\Gareth Finch\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\lib\agw\ultimatelistctrl.py", line 11990, in HitTest
    return self._mainWin.HitTest(x, y)
  File "C:\Users\Gareth Finch\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\lib\agw\ultimatelistctrl.py", line 10151, in HitTest
    newItem, flags = self.HitTestLine(current, x, y)
  File "C:\Users\Gareth Finch\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\lib\agw\ultimatelistctrl.py", line 6812, in HitTestLine
    newItem = self.GetParent().GetItem(line, col)
  File "C:\Users\Gareth Finch\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\lib\agw\ultimatelistctrl.py", line 11243, in GetItem
    return self._mainWin.GetItem(item, col)
  File "C:\Users\Gareth Finch\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\lib\agw\ultimatelistctrl.py", line 8964, in GetItem
    if item._itemId < 0 or item._itemId >= self.GetItemCount():
AttributeError: 'float' object has no attribute '_itemId'

I have found that the cause seems to be in this section of the Hittest code in the ultimatelistctrl.py;
    def HitTest(self, x, y):
        """
        HitTest method for a :class:`UltimateListCtrl`.

        :param `x`: the mouse `x` position;
        :param `y`: the mouse `y` position.

        :see: :meth:`~UltimateListMainWindow.HitTestLine` for a list of return flags.
        """
        x, y = self.CalcUnscrolledPosition(x, y)
        count = self.GetItemCount()

        if self.InReportView():
            if not self.HasAGWFlag(ULC_HAS_VARIABLE_ROW_HEIGHT):
                current = y/self.GetLineHeight()

Current is being defined as a float.  The rest of the code doesnt like this.  If you add a line;
current = int(current), everything seems to work.

**Comment by RobinD42** [comment]
Ah, good ol' [PEP 238](https://www.python.org/dev/peps/pep-0238/)...

Thanks for reporting this.
