### ISSUE TITLE
wxdemo and certificate issues

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#545]
**Operating system**: OSX
**wxPython version**: 4.0.0b2
**Stock or custom build**: 
**Python version**: 3.6, 2.7
**Stock or custom build**: anaconda

**Description of the problem**:

From wxPython-users:

Hi Robin,

Thanks so much!  This is working well for me with Anaconda Python 3.6 and 2.7 on OSX (the only system I've tested so far), except that the new wxdocs and wxdemo (which look very, very handy) don't work for me.  First, I got

    ~>~/anaconda3/bin/pythonw ~/anaconda3/bin/wxdemo
    Traceback (most recent call last):
      File "/Users/Newville/anaconda3/bin/wxdemo", line 7, in <module>
        from wx.tools.wxget_docs_demo import demo_main
      File "/Users/Newville/anaconda3/lib/python3.6/site-packages/wx/tools/wxget_docs_demo.py", line 47, in <module>
        import wxget
    ModuleNotFoundError: No module named 'wxget'

I think that was probably meant to be `from . import wxget`.   Making that change I then get

    ~>~/anaconda3/bin/pythonw ~/anaconda3/bin/wxdemo
    sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0) 3.6.2 |Anaconda custom (x86_64)| (default, Jul 20 2017, 13:14:59)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] ['/Users/Newville/anaconda3/bin/wxdemo']
    Launch Demo for wxPython V4.0.0b2
    Looking for wxPython-demo-4.0.0b2 at /Users/Newville/Library/Application Support/wxPython
    Looking for cached /Users/Newville/Library/Application Support/wxPython/wxDocsDemoCache/4.0.0b2/wxPython-demo-4.0.0b2.tar.gz

and the Dialog with "Download Prompt" pops up asking if I want to download the demo tarball.  Hitting 'Yes' results in the traceback below, ending with

      File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 688, in do_handshake
        match_hostname(self.getpeercert(), self.server_hostname)
      File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 321, in match_hostname
        % (hostname, ', '.join(map(repr, dnsnames))))
    ssl.CertificateError: hostname 'extras.wxpython.org' doesn't match either of 'alldunn.com', 'www.alldunn.com'

When I go to that site in a regular browser I see "connection not secure" messages, as if https is not certified.  If I accept the risk and proceed anyway, it doesn't seem like the place I was looking for...

Hope that helps, and thanks very much!

--Matt
Full traceback:

```
Traceback (most recent call last):
  File "/Users/Newville/anaconda3/bin/wxdemo", line 11, in <module>
    sys.exit(demo_main())
  File "/Users/Newville/anaconda3/lib/python3.6/site-packages/wx/tools/wxget_docs_demo.py", line 159, in demo_main
    pd['Demo_Name'], pd['Ext'])
  File "/Users/Newville/anaconda3/lib/python3.6/site-packages/wx/tools/wxget_docs_demo.py", line 107, in get_item
    cached = wxget.download_file(url, cache, True)
  File "/Users/Newville/anaconda3/lib/python3.6/site-packages/wx/tools/wxget.py", line 101, in download_file
    url_res = urllib2.urlopen(url)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/Newville/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/Newville/anaconda3/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 688, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/Users/Newville/anaconda3/lib/python3.6/ssl.py", line 321, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'extras.wxpython.org' doesn't match either of 'alldunn.com', 'www.alldunn.com'
```
 
--Matt Newville

**Comment by RobinD42** [comment]
Thanks for the report. It does look like there are some problems with wxget and secure sites. 

However accessing the URL via a browser should show as secure. It does have an SSL certificate although it's issued by the newish Let's Encrypt system so maybe your system's root certificates needs to be updated? OTOH, it appears to be trying to use alldunn.com's certificate, which is on the same IP address, so perhaps you are behind a proxy server or something that is caching certs by IP instead of hostname...

![snap002](https://user-images.githubusercontent.com/808502/30656354-aeaebc08-9de8-11e7-9773-8e4bc1471f04.png)

**Comment by GadgetSteve** [comment]
@RobinD42 Good idea, possibly with either a fallback to the current functionality or with logic such as if requests is installed use it but otherwise try without it and if that fails prompt the user for permission to install.

I'll try to find a few minutes before Monday to give it a try.

**Comment by GadgetSteve** [comment]
@RobinD42 I don't think that requests will make a lot of difference here as on my test platforms, (Windows 10 home & Windows 7 pro when not behind a firewall it works fine from the https: address and not at all from behind a firewall, (unfortunately I don't have a Mac for testing). I am going to experiment with using `pip download` as many people will have to have configured pip to work, _if they haven't they probably have more to worry about than this_.

**Comment by GadgetSteve** [comment]
The above pull request should resolve the majority of issues by using wget on platforms that support it.
