### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by mark-summerfield** [wxWidgets/Phoenix#570]
These occurred simply by running the demo and trying out each thing in it.

I have been trying the Phoenix demo on Windows 7 using Py3.4 and wxPython 4b2. If I just try things out it seems to work okay. But if I click Help->About, it always crashes -- but not always instantly. Here's some info that I hope will help:

Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
>>> wx.version()
'4.0.0b2 msw (phoenix)'

Problem signature:
  Problem Event Name:    APPCRASH
  Application Name:    pythonw.exe
  Application Version:    0.0.0.0
  Application Timestamp:    5676ff9d
  Fault Module Name:    MSVCR100.dll
  Fault Module Version:    10.0.40219.1
  Fault Module Timestamp:    4d5f034a
  Exception Code:    40000015
  Exception Offset:    00000000000761c9
  OS Version:    6.1.7601.2.1.0.768.3
  Locale ID:    2057
  Additional Information 1:    09f8
  Additional Information 2:    09f8fea043a2932ddd276f62ba23d7b0
  Additional Information 3:    49f6
  Additional Information 4:    49f69ed0067c624c3c5764d171ab8f05

V:\tmp\wxPython-demo-4.0.0b2\demo>py demo.py
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 8699, in OnRender
    if not self._frame or self._frame.IsBeingDeleted():
  File "C:\Python34\lib\site-packages\wx\core.py", line 2169, in _Window___nonzero__
    import wx.siplib
RuntimeError: maximum recursion depth exceeded while calling a Python object

V:\tmp\wxPython-demo-4.0.0b2\demo>py demo.py
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 8699, in OnRender
    if not self._frame or self._frame.IsBeingDeleted():
  File "C:\Python34\lib\site-packages\wx\core.py", line 2169, in _Window___nonzero__
    import wx.siplib
RuntimeError: maximum recursion depth exceeded while calling a Python object

V:\tmp\wxPython-demo-4.0.0b2\demo>py demo.py
Traceback (most recent call last):
  File "agw\FoldPanelBar.py", line 211, in OnFoldPanelBarDrag
    if event.GetDragStatus() == wx.SASH_STATUS_OUT_OF_RANGE:
AttributeError: 'module' object has no attribute 'SASH_STATUS_OUT_OF_RANGE'
Traceback (most recent call last):
  File "agw\PersistentControls.py", line 89, in OnExample2
    frame = PersistentFrame2(self, _title + "- Example 2", (700, 500))
  File "agw\PersistentControls.py", line 391, in __init__
    self.DoLayout(dummyPanel)
  File "agw\PersistentControls.py", line 407, in DoLayout
    self.notebook.AddPage(self.CreateListCtrl(), "wx.ListCtrl")
  File "agw\PersistentControls.py", line 458, in CreateListCtrl
    idx = listCtrl.InsertItem(sys.maxsize, text%(row+1, 1), 0)
wx._core.wxAssertionError: C++ assertion "rv != -1" failed at ..\..\src\msw\listctrl.cpp(1730) in wxListCtrl::InsertItem(): failed to insert an item in wxListCtrlSetTitle Floating!
Floating!
C:\Python34\lib\site-packages\wx\lib\floatcanvas\ScreenShot.py:1783: wxPyDeprecationWarning: Call to deprecated item BitmapFromImage. Use :class:`wx.Bitmap` instead return BitmapFromImage(getScreenShotImage())

V:\tmp\wxPython-demo-4.0.0b2\demo>py demo.py
Traceback (most recent call last):
  File "RichTextCtrl.py", line 320, in OnFileViewHTML
    if not handler.SaveStream(self.rtc.GetBuffer(), stream):
AttributeError: 'RichTextHTMLHandler' object has no attribute 'SaveStream'
GetTextLength():  1183 1152
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\wx\core.py", line 3189, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "Joystick.py", line 928, in Calibrate
    self.info.Calibrate()
  File "Joystick.py", line 603, in Calibrate
    self.MaxAxis.SetValue(str(s.GetMaxAxes()))
AttributeError: 'Joystick' object has no attribute 'GetMaxAxes'
Traceback (most recent call last):
  File "Joystick.py", line 642, in onPaint
    self.ShowValue(wx.PaintDC(self), evt)
  File "Joystick.py", line 651, in ShowValue
    wx.Gauge.OnPaint(self, evt)
AttributeError: type object 'Gauge' has no attribute 'OnPaint'
Traceback (most recent call last):
  File "Joystick.py", line 642, in onPaint
    self.ShowValue(wx.PaintDC(self), evt)
  File "Joystick.py", line 651, in ShowValue
    wx.Gauge.OnPaint(self, evt)
AttributeError: type object 'Gauge' has no attribute 'OnPaint'
GetText():

V:\tmp\wxPython-demo-4.0.0b2\demo>demo.py

Traceback (most recent call last):
  File "GLCanvas.py", line 114, in OnPaint
    self.InitGL()
  File "GLCanvas.py", line 234, in InitGL
    glutInit(sys.argv)
  File "C:\Python34\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Python34\lib\site-packages\OpenGL\platform\baseplatform.py", line 407, in __ca
l__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for
bool(glutInit) before calling

**Comment by thetestgame** [comment]
I also have a similar issue due to a recursion error when importing ``wx.siplib``. I get it when trying to use the scrolledpanel object.

**Comment by RobinD42** [comment]
@thetestgame, platform, wx version and python version?

**Comment by mesalu** [comment]
@blitzmann, have you made any progress on your Pyfa issue? 
Is it related to importing `wx.siplib`?
I've been unable to reproduce this one.

**Comment by blitzmann** [comment]
I have not. Unfortunately it kinda fell off my radar, and seemed to affect os x 10.13 which I dont have access to. Also been busy with other priorities. If you find out more info, please let me know in the issue!

**Comment by Apteryks** [comment]
For me the demo code doesn't run.  Per demo/README.txt:
```
~/src/wxpython/demo [env]$ python demo.py
Traceback (most recent call last):
  File "/home/maxim/src/wxpython/demo/demo.py", line 3, in <module>
    import Main
  File "/home/maxim/src/wxpython/demo/Main.py", line 75, in <module>
    import version
ModuleNotFoundError: No module named 'version'
```

Seems it wants the version.py modules from wx/py... let's try again:
```
~/src/wxpython/demo [env]$ PYTHONPATH=../wx/py python demo.py
Traceback (most recent call last):
  File "/home/maxim/src/wxpython/demo/Main.py", line 2664, in OnInit
    if LooseVersion(version.VERSION_STRING) != LooseVersion(wx.VERSION_STRING):
AttributeError: module 'version' has no attribute 'VERSION_STRING'
OnInit returned false, exiting...
```

No luck.  How is demo.py supposed to be run as of wxPython 4.2.0 ?
```
