### ISSUE TITLE
wx.lib.masked.IpAddrCtrl broken on GTK

### ISSUE THREAD

**Issue by jubnzv** [wxWidgets/Phoenix#639]
**Operating system**: Debian GNU/Linux 9
**wxPython version**: 4.0.0b2
**Stock or custom build**: stock
**Python version**: 2.7.13
**Stock or custom build**: stock

**Description of the problem**:
`wx.lib.masked.IpAddrCtrl` works incorrectly on GTK. With my simple test I have same behavior of this element:
![ipaddrctrl](https://user-images.githubusercontent.com/12023585/33517461-aef26250-d795-11e7-8df7-25ff2a24b695.gif)

Source code of this test:
```python
import wx
import wx.lib.masked as masked

class MainWindow(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title, size=(500,500))

        self.ipaddr1 = masked.IpAddrCtrl(self, -1, style=wx.TE_PROCESS_TAB)

        self.grid_ip = wx.FlexGridSizer(cols=2, vgap=10, hgap=10)
        self.grid_ip.Add(self.ipaddr1, 0, wx.ALIGN_LEFT)    
        self.sizer = wx.BoxSizer(wx.VERTICAL)
        self.sizer.Add(self.grid_ip, 0, wx.ALIGN_LEFT | wx.ALL, border=5)
        self.SetSizer(self.sizer)    
        self.Bind(wx.EVT_TEXT, self.OnIpAddrChange, id=self.ipaddr1.GetId())    
        self.Show(True)

    def OnIpAddrChange(self, event):
        print(self.ipaddr1.GetAddress())
        print(self.ipaddr1.IsValid())

if __name__ == '__main__':
    app = wx.App(False)
    frame = MainWindow(None, "IpAddrCtrl sample")
    app.MainLoop()
```
The same problem occurs when I use more complicated [MaskedEditControls](https://github.com/wxWidgets/Phoenix/blob/master/demo/MaskedEditControls.py) demo.

The problem is specific only on GTK platform: on Win32 this app works perfectly. After some debugging I found out that the difference in GTK/Win versions in additional `EVT_TEXT` event call that occurs in `IpAddrCtrl` when I try to edit selected text region. That causes unnecessary `_OnTextChange` event handler call, that brokes input. That strange behavior [described](https://wiki.wxpython.org/wxPython%20Platform%20Inconsistencies#wxTextCtrl.SetValue.28.29_from_within_Event_Handlers) on wxPython wiki and [commented](https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/masked/maskededit.py#L2949) in a sources of base class for `IpAddrCtrl`, but currently a have no idea how to fix it.

In wxPython classic there is same troubles.
I also dublicate this error on [stackoverflow](https://stackoverflow.com/questions/47570104/ipaddrctrl-broken-on-gtk).

Can anybody advice me how I should fix it? Or maybe I doing something wrong?

**Comment by esitarski** [comment]
I ran into the same problem.  This is also broken on Mac.
For what it is worth, my "very ugly but quick and dirty" workaround was to substitute a regular TextCtrl for an IpAddrCtrl on all platforms but Windows.

    if 'WXMSW' in wx.Platform:
        IpAddrCtrl = masked.IpAddrCtrl
    else:
        class IpAddrCtrl( wx.TextCtrl ):
            def GetAddress( self ):
                return self.GetValue()

Then use "IpAddrCtrl" in your code, not "masked.IpAddrCtrl".  I recognize this defeats the purpose of IpAddrCtrl and does nothing to fix other masked use cases.

**Comment by esitarski** [comment]
This is the error I get on Mac:

Traceback (most recent call last): 
 File "/usr/local/lib/python2.7/dist-packages/wx/lib/masked/maskededit.py", line 3086, in _OnChar 
   if keep_processing and self._isCharAllowed( char, pos, checkRegex = True ): 
 File "/usr/local/lib/python2.7/dist-packages/wx/lib/masked/maskededit.py", line 4743, in _isCharAllowed 
   newvalue, ignore, ignore, ignore, ignore = self._insertKey(char, at, sel_start, sel_to, value, allowAutoSelect=True) 
 File "/usr/local/lib/python2.7/dist-packages/wx/lib/masked/maskededit.py", line 5146, in _insertKey 
   if fstr[0] in erasable_chars or (self._signOk and field._index == 0 and fstr[0] in ('-','(')): 
IndexError: string index out of range

**Comment by jensgoe** [comment]
Same heppens with wx.lib.masked.timectrl.TimeCtrl. And even with wxPython (classic) My guess is that GTK3 has somehow different event timings. Retrieving the value of a TextCtrl with GetValue() in an OnChar event already returns the new text value which was probably the value before the key press on GTK2. But thats only an assumption. I currently don't have GTK2 running to check this.

**Comment by tmerr** [comment]
Looks like @jensgoe is right, adding this to the top of the test code seems to fix it:

```_oldinit = masked.IpAddrCtrl.__init__
def patched_init(self, *args, **kwargs):
    _oldinit(self, *args, **kwargs)
    self.Unbind(wx.EVT_CHAR)
    self.Bind(wx.EVT_CHAR_HOOK, self._OnChar)
masked.IpAddrCtrl.__init__ = patched_init
```

The change should really be in `BaseMaskedTextCtrl._PostInit`, will have to check how it affects other controls.

**Comment by mesalu** [comment]
Patching the event dispatcher is very probably out of the question. 
However: Pull requests to normalize behavior across all ports would be greatly appreciated. :) 
It seems `masked` has been in need of some maintenance for a while.
