### ISSUE TITLE
Entry points for wx tools fail with import error

### ISSUE THREAD

**Issue by nehaljwani** [wxWidgets/Phoenix#650]
**Operating system**: Mac OS X 10.9.5 13F1911
**wxPython version**: 4.0.0b2
**Stock or custom build**: Stock
**Python version**: 3.6.3
**Stock or custom build**: Custom (Anaconda Distribution)

**Description of the problem**:

```
(test) mbpro:~ nwani$ wxdocs --help
Traceback (most recent call last):
  File "/Users/nwani/m3/envs/test/bin/wxdocs", line 7, in <module>
    from wx.tools.wxget_docs_demo import docs_main
  File "/Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/wxget_docs_demo.py", line 47, in <module>
    import wxget
ModuleNotFoundError: No module named 'wxget'

(test) mbpro:~ nwani$ wxdemo --help
Traceback (most recent call last):
  File "/Users/nwani/m3/envs/test/bin/wxdemo", line 7, in <module>
    from wx.tools.wxget_docs_demo import demo_main
  File "/Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/wxget_docs_demo.py", line 47, in <module>
    import wxget
ModuleNotFoundError: No module named 'wxget'

(test) mbpro:~ nwani$ img2png --help
Traceback (most recent call last):
  File "/Users/nwani/m3/envs/test/bin/img2png", line 7, in <module>
    from wx.tools.img2png import main
  File "/Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/img2png.py", line 40, in <module>
    import  img2img
ModuleNotFoundError: No module named 'img2img'

(test) mbpro:~ nwani$ img2xpm --help
Traceback (most recent call last):
  File "/Users/nwani/m3/envs/test/bin/img2xpm", line 7, in <module>
    from wx.tools.img2xpm import main
  File "/Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/img2xpm.py", line 39, in <module>
    import  img2img
ModuleNotFoundError: No module named 'img2img'

(test) mbpro:~ nwani$ ls -l /Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/{wxget,img2img}.py
-rw-r--r--  1 nwani  owner  2245 Dec 17 04:54 /Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/img2img.py
-rw-r--r--  1 nwani  owner  5746 Dec 17 04:54 /Users/nwani/m3/envs/test/lib/python3.6/site-packages/wx/tools/wxget.py
```

**Comment by RobinD42** [comment]
Fixed in #548
