### ISSUE TITLE
Phoenix demo - not able to start

### ISSUE THREAD

**Issue by infinity77** [wxWidgets/Phoenix#72]
I have tried to run the Phoenix demo, both with Phoenix compiled by me from source and also with the pre-compiled snapshot build named "wxPython_Phoenix-3.0.3.dev1964+f780b21"

I get this, no matter what I do:

D:\MyProjects\Phoenix\demo>python Main.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\wx\core.py", line 1955, in Notify
    self.notify()
  File "C:\Python27\lib\site-packages\wx\core.py", line 3034, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "Main.py", line 2601, in ShowMain
    frame = wxPythonDemo(None, "wxPython: (A Demonstration)")
  File "Main.py", line 1531, in __init__
    self.SetOverview(self.overviewText, mainOverview)
  File "Main.py", line 2130, in SetOverview
    self.nb.SetPageText(0, os.path.split(name)[1])
SystemError: ..\Objects\longobject.c:998: bad argument to internal function

I have checked that the arguments of SetPageText make sense (int and str). I am unclear what the message exactly means...

This is on Windows 10 64 bit, Python 27 64 bit.

Andrea.

**Comment by infinity77** [comment]
Shame on me, it's a Python bug for 2.7.8, which of course needs to be the version on my home PC...

https://bugs.python.org/issue23842

Sorry for the noise.
