### ISSUE TITLE
"python build.py dox etg --nodoc sip build" fails due to "make: *** No rule to make target '/builds/krichter/Phoenix/ext/wxWidgets/src/jpeg/jaricom.c', needed by 'wxjpeg_jaricom.o'.  Stop."

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#789]
**Operating system**: Ubuntu 17.10
**wxPython version**: 4.1.0a1
**Stock or custom build**: custom build
**Python version**: 2.7.13 and 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
`python build.py dox etg --nodoc sip build` fails due to

```
make: *** No rule to make target '/builds/krichter/Phoenix/ext/wxWidgets/src/jpeg/jaricom.c', needed by 'wxjpeg_jaricom.o'.  Stop.
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "build.py", line 1317, in cmd_build_wx
    wxbuild.main(wxDir(), build_options)
  File "/builds/krichter/Phoenix/buildtools/build_wxwidgets.py", line 498, in main
    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
  File "/builds/krichter/Phoenix/buildtools/build_wxwidgets.py", line 85, in exitIfError
    raise builder.BuildError(msg)
BuildError
g...
Finished command: sip (1m21.745s)
Running command: build
Running command: build_wx
wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
Configure options: ['--enable-unicode', '--with-gtk=3', '--with-opengl', '--enable-sound', '--enable-graphics_ctx', '--enable-mediactrl', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--with-sdl']
/builds/krichter/Phoenix/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --with-opengl --enable-sound --enable-graphics_ctx --enable-mediactrl --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --with-sdl
make --jobs=8
Error building
ERROR: failed building wxWidgets
Finished command: build_wx (14.302s)
Finished command: build (14.302s)
```

on many Debian-based OS, I provided an overview at https://gitlab.com/krichter/Phoenix/pipelines/18976530. In case this failure occurs due to a missing prerequisite, it'd be nice if the configure script was improved so that it fails with a verbose, helpful error message.

**Comment by RobinD42** [comment]
wxWidgets now has git submodules so you need to init them recursively:

```
    git submodule update --init --recursive
```

**Comment by krichter722** [comment]
> wxWidgets now has git submodules so you need to init them recursively:

That's what I'm doing: https://gitlab.com/krichter/Phoenix/blob/gitlab-ci/.gitlab-ci.yml

**Comment by RobinD42** [comment]
I don't' see any `--recursive` flags there.
