### ISSUE TITLE
Broken wx.adv

### ISSUE THREAD

**Issue by HelioGuilherme66** [wxWidgets/Phoenix#86]
Just compiled latest merge (14a1dddde436cd9386cf97b12408d0bb1bffd707) in Fedora 22 x64 GTK3, and the demo.py is failing with wx.adv module.
```
[helio@localhost demo]$ ./demo.py 
Traceback (most recent call last):
  File "./demo.py", line 3, in <module>
    import Main
  File "/opt/Phoenix/demo/Main.py", line 62, in <module>
    import wx.adv
  File "/usr/lib64/python2.7/site-packages/wx-3.0.3-dev-gtk3/wx/adv.py", line 6, in <module>
    from ._adv import *
ImportError: /usr/lib64/python2.7/site-packages/wx-3.0.3-dev-gtk3/wx/_adv.so: symbol _ZTI21wxNotificationMessage, version WXU_3.0 not defined in file libwx_gtk3u_adv-3.0.so.0 with link time reference
```
(Some demos launch fine, for example: RearrangeDialog.py and FontDialog.py)

Unit tests are failing!
```
[helio@localhost Phoenix]$ ./b test
/usr/bin/python
Build using: "/usr/bin/python"
2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
Python's architecture is 64bit
cfg.VERSION: 3.0.3

Running command: test
"/usr/bin/python" unittests/runtests.py  
wx.version: 3.0.3 gtk3 (phoenix)
pid: 27597
Traceback (most recent call last):
  File "unittests/runtests.py", line 162, in <module>
    testRunner=MyTestRunner, testLoader=MyTestLoader())
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/opt/Phoenix/unittests/test_lib_agw_balloontip.py", line 5, in <module>
    import wx.lib.agw.balloontip as BT
  File "/usr/lib64/python2.7/site-packages/wx-3.0.3-dev-gtk3/wx/lib/agw/balloontip.py", line 171, in <module>
    import wx.adv
  File "/usr/lib64/python2.7/site-packages/wx-3.0.3-dev-gtk3/wx/adv.py", line 6, in <module>
    from ._adv import *
ImportError: /usr/lib64/python2.7/site-packages/wx-3.0.3-dev-gtk3/wx/_adv.so: symbol _ZTI21wxNotificationMessage, version WXU_3.0 not defined in file libwx_gtk3u_adv-3.0.so.0 with link time reference
Command '"/usr/bin/python" unittests/runtests.py  ' failed with exit code 1.
Finished command: test (2.179s)
Done!
```
@RobinD42 please tell me how can I help.

**Comment by HelioGuilherme66** [comment]
The errors were gone after merging ext/wxWidgets WX_3_0_BRANCH (commit 4c6f6059a496b676a10ea016164946d923780519) and recompiled (new bugs appear at demo.py).

**Comment by RobinD42** [comment]
It may have just been the fact that a wxWidgets rebuild was forced rather than updating the wx revision.  I don't see anything in the recent changes that should have had any effect on wxNotificationMessage, but it is probably time for a merge anyway so I'll take care of that later today.
