### ISSUE TITLE
My pip(python 2.7.15) report errors after I install wxpython4.0.0 

### ISSUE THREAD

**Issue by Iverson-Zhou** [wxWidgets/Phoenix#861]
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\python27\lib\site-packages\pip\vcs\subversion.py", line 9, in <module>
    from pip.index import Link
  File "c:\python27\lib\site-packages\pip\index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "c:\python27\lib\site-packages\pip\wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "c:\python27\lib\site-packages\pip\_vendor\distlib\scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "c:\python27\lib\site-packages\pip\_vendor\distlib\compat.py", line 467, in <module>
    from html import escape
  File "C:\Python27\Lib\site-packages\wx\html.py", line 18, in <module>
    from ._html import *
ValueError: Attempted relative import in non-package

**Comment by RobinD42** [comment]
What was the pip command-line you used? What is the current folder when you run it? Is your Python 2.7.15 the stock one from python.org or some other distribution? Has wxPython been installed in this Python environment before?

**Comment by RobinD42** [comment]
My guess is that he was in the `C:\Python27\Lib\site-packages\wx` folder, or it was somehow on the `sys.path`, when running pip, and so its import was mistakenly finding wx's html module. If then this is a non-issue.

**Comment by infinity77** [comment]
@swt2c Python 2.7 is gone.
