### ISSUE TITLE
wx.dataview.DataViewCtrl.GetSelections() failed in callback function

### ISSUE THREAD

**Issue by Nutznieser** [wxWidgets/Phoenix#952]
**Operating system**: Windows, Linux
**wxPython version**: 4.0.3
**Stock or custom build**:
**Python version**: 3.6.6
**Stock or custom build**:

**Description of the problem**:

If you use the `wx.dataview.DataViewCtrl.GetSelections()` inside an event callback function it will fail in the first example below. But in the second example (compare the tiny difference) it will work. I can't understand why and if that behavior is correct or a bug?

For testing the code you can copy it to the file `DVC_DataViewModel.py` of the wxPython demo.

This will fail:
```python
        ...

        self.dvc.Bind(dv.EVT_DATAVIEW_SELECTION_CHANGED, self.OnSelChanged)

    def OnSelChanged(self, evt):
        items = list(self.dvc.GetSelections())
        objects = [self.model.ItemToObject(item) for item in items]
        print(objects)
        evt.Skip()

    ...
```

and it is raising the following error:
```
Traceback (most recent call last):
  File "/home/harry/.wxPyDemo/modified/DVC_DataViewModel.py", line 303, in OnSelChanged
    objects = [self.model.ItemToObject(item) for item in items]
  File "/home/harry/.wxPyDemo/modified/DVC_DataViewModel.py", line 303, in <listcomp>
    objects = [self.model.ItemToObject(item) for item in items]
  File "/home/harry/.local/lib/python3.6/site-packages/wx/dataview.py", line 85, in ItemToObject
    return self.mapper[oid]
  File "/usr/lib64/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 94885105920880
```

But the next example will work! I think it depends on the binding to a variable BEFORE forming a list from the selected objects.
```python
        ...

        self.dvc.Bind(dv.EVT_DATAVIEW_SELECTION_CHANGED, self.OnSelChanged)

    def OnSelChanged(self, evt):
        items = self.dvc.GetSelections()
        objects = [self.model.ItemToObject(item) for item in list(items)]
        print(objects)
        evt.Skip()

    ...
```

In more complex code it can be difficult to handle this problem. To solves it in my own code I add the following method to my instance of `wx.dataview.DataViewCtrl`. It binds the selection to a class attribute before returning it. In this way no later calls of `GetSelection()` will never fail in any circumstance. But I don't know if that is the right way?

```python
   def GetSelections(self):
        self.sel = super().GetSelections()
        return self.sel
```

**Comment by RobinD42** [comment]
There seems to be something fishy going on with the lifetime of the `DataViewItem` objects so I'll try to see what's happening there. 

In the meantime, the object returned by `GetSelections` is iterable, so there is no need to convert it to a list first. So this should also work:

```python
    objects = [self.model.ItemToObject(item) for item in self.dvc.GetSelections()]
```

Perhaps that workaround is easier to apply to your application code.

**Comment by Nutznieser** [comment]
@RobinD42 

> In the meantime, the object returned by GetSelections is iterable, so there is no need to convert it to a list first. 

Yes, I know. In my original code this problem is more complex. So I created only a small and simplified test example for this thread. But thanks for your hint!
